### ISSUE TITLE
Support securitySchemes

### ISSUE THREAD

**Issue by analytically** [raml2html/raml2html#10]
https://github.com/raml-org/raml-spec/blob/master/08_security.md

**Comment by k2xl** [comment]
Is the lock icon supposed to be clickable?

**Comment by kevinrenskers** [comment]
No, but it is still supposed to show the "secured by" details in the modal. Thanks for the reminder, I'll try to get on this asap.

**Comment by joshavant** [comment]
Just ran into problems with this today. I sure would like this feature, too!

Here's a basic sample test RAML for this feature that I came up with, to help test the feature:
```
#%RAML 0.8
---
title: Raml2Html Test File
version: v0.1
baseUri: https://github.com/joshavant
securitySchemes:
    - foo_security:
        description: Foobar
        type: x-FooSecurity
        describedBy:
            headers:
                X-Auth-Token:
                    description: Some auth token
                    type: string
            responses:
                401:
                    description: Auth token was bad

/users:
  /{userID}/test:
    put:
      securedBy: [foo_security]
      responses:
        200:
          description: Success.
```

**Comment by schmkr** [comment]
Just noticed that when using e.g. `securedBy: [null, oauth_2_0]` to indicate that the method may be called without applying any securityScheme (see [this part of the spec](http://raml.org/spec.html#usage-applying-a-security-scheme-to-an-api)), the `null` value is not displayed as `null`, but as an empty string.

**Comment by davidfells** [comment]
Headers in the security scheme do not appear anywhere in the generated docs - why is that?

**Comment by dave-irvine** [comment]
@kevinrenskers I've also noticed that if you secure an entire API by using `securedBy` at the root, and then override this with `securedBy: [null]` on a method, you still end up with the Padlock view on that method in the docs.

I've managed to fix this by adding in a hack in raml2obj so that if it finds a `securedBy` element it strips out any nulls. This trickles down to eventually give you a `method.securedBy.length` value of 0 which removes the Padlock.

As far as I can tell this is spec compliant, but wondering if this sort of change would break the expected behaviour for people like @schmkr.

Any thoughts?

**Comment by nickveenhof** [comment]
See #167 , does that solve this issue?

**Comment by nmors** [comment]
@nickveenhof In my opinion no, it wouldn't. However it is the first step towards fully supporting securitySchemes.

For me, when defining an oauth2 securityScheme with scopes, the output does not parse the scopes object and simply shows:
```
 Secured by [object Object]
```
If no scopes are defined, then it works okay. But really, I think #165 should be implemented before closing this.

e.g. the securedBy format below, is still unsupported:
```
        securedBy: [oauth_2_0: { scopes: [ ADMINISTRATOR ] } ]
```

**Comment by kevinrenskers** [comment]
2.5.0 has multiple fixes related to security schemes and scopes. Is there anything left for this ticket or can it be closed?
