### ISSUE TITLE
A simple view of any schemas would be great

### ISSUE THREAD

**Issue by gconz** [raml2html/raml2html#130]
I know you said that there are no plans to implement this feature at this time (https://github.com/kevinrenskers/raml2html/issues/91), but I, and I am sure others, would love to see.  We are using your tool to generate the primary documentation of an API for implementors, and that documentation is really incomplete without the schemas.

**Comment by kevinrenskers** [comment]
I understand, but as I don't have a need for this feature myself and I'm also low on free time, this would really need to be developed by a contributor. I'd love to see more pull requests! 

I think some kind of hooks system where you're able to manipulate pieces of the template or RAML object while still using the default templates would be very nice. But like I said, this isn't even on my todo list.

**Comment by kylehayes** [comment]
Definitely want this as well. @gconz, when you say simple view, would even a table of the attributes, their types, defaults, examples etc could be a good start?

**Comment by dwcramer** [comment]
IMO, generating schema documentation is a job for a different tool. raml2html should be able to generate links into the schema documentation (in fact, we've modified our fork of it to make that possible), but there's no way that raml2html as a project could do a good job of generating human readable docs from all the possible varieties of JSON schema (which is a trainwreck anyway) and XML schemas (w3c, relaxng). While most schemas for request and response bodies are simple, some are not and involve recursion and other complicated constructs.  Each schema vocabulary generally has its own doc generation tool maintained by its own community.

**Comment by kylehayes** [comment]
@dwcramer, that's a fair point. I like the idea of just generating links to schema documentation rather than embedding it directly in the rendered output. There are some parsers and "documentation" generators that might be good enough to start with: http://json-schema.org/implementations.html

**Comment by dwcramer** [comment]
@kylehayes Yes, the trick now is that there's no facility in the raml vocabulary for including links to schema docs other than putting the link in the description of the method and there's currently no mechanism for extending raml. In our fork, we replaced the link to the schema itself with a link to our generated schema docs and render that in the output. I'm sure this will break other raml-aware tools if we tried to use our raml with them though.

**Comment by kevinrenskers** [comment]
Closing this, going to create a new umbrella-issue for all things schemas and $ref.

**Comment by agm1984** [comment]
Does this functionality exist yet?

I can't seem to get my schemas to render. I'm in that unfortunate position where I don't know if my syntax is horribly incorrect or RAML2HTML just doesn't show the schema like it does the examples.

**Comment by sichvoge** [comment]
I don't think that this is implemented, I am afraid.

**Comment by kevinrenskers** [comment]
Please see #327
