### ISSUE TITLE
Is there a way to print parsing errors?

### ISSUE THREAD

**Issue by DataGreed** [raml2html/raml2html#159]
Right now the raml2html returns either 0 or 1 exit status, that alerts you of a present error in the markup. Thoigh, I didn't find any options to show the actual errors (lines with parsing errors would be great as a start) - is there a way to enable it?

**Comment by DataGreed** [comment]
Btw, I am using pyCharm (intellij Idea basically) with yaml plug-in, so finding errors is really difficult :)

**Comment by ericjsilva** [comment]
@DataGreed have you looked at API Workbench (http://apiworkbench.com/).  Uses the Atom editor. I have found good results with it. Especially when validating syntax.

**Comment by DataGreed** [comment]
@ericjsilva thank you for the reply. I've found out that if the parsing fails the exception output is being written to output file. So, I've just added a script that checks the file and if it contains less than 10 lines, it just prints it out on the console, so I know that it's an error :)

**Comment by DataGreed** [comment]
@ericjsilva wow, workbench looks good, though. Thanks you!

**Comment by kevinrenskers** [comment]
2.2.0 is now printing errors to STDERR, can you check if that helps?

**Comment by ryanpitt** [comment]
Can confirm errors print nicely for the latest version on Debian.
