### ISSUE TITLE
RAML2HTML Security Schema Details Missing

### ISSUE THREAD

**Issue by yogirackspace** [raml2html/raml2html#160]
I am using RAML2HTML -V 2.1.2.

I have my own security schema section and in the earlier versions of raml2html the security schema details were automatically rendered in the documents.

However the new raml2html plugins have stopped including the schema details

securitySchemes:
  - internalIdentity: !include ../my-own-security-scheme.yaml

Any help would be appreciated.

**Comment by dman777** [comment]
:+1:  I have this issue also

**Comment by nickveenhof** [comment]
See #162

**Comment by nickveenhof** [comment]
Rebased it against develop branch. See #167

**Comment by nickveenhof** [comment]
Can you check again and close if this is solved now?

**Comment by oniofchaos** [comment]
@nickveenhof I'm having a similar issue to OP. I used your develop branch and I see the basic security info but not the `queryParameters` section, which it looks like #167 did not include.

**Comment by kevinrenskers** [comment]
Pretty sure this ticket can be closed now that 2.5.0 is released, correct?
