### ISSUE TITLE
Expand documentation content !include

### ISSUE THREAD

**Issue by rymndhng** [raml2html/raml2html#164]
If I have the following, when using `raml2doc` on the filesystem, it resolves the content properly.

``` raml
documentation:
  - title: Getting Started
    content: !include docs/getting_started.txt
```

However, when I try to do this using a http request, the final content is empty.

```
raml2html -i http://localhost:8080/raml/v0.4/api.raml -o dist/index.html
```

Oddly enough, it does request `http://localhost:8080/raml/v0.4/docs/getting_started.txt`, but `raml2doc` does not appear to use the content.

**Comment by kevinrenskers** [comment]
What happens is that raml2html downloads the remote raml file `http://localhost:8080/raml/v0.4/api.raml` but then your raml file specifies a relative path `docs/getting_started.txt` which isn't on the filesystem.

You should thus use absolute url's as the include path, or just use local files. I'd definitely recommend using local files.

**Comment by rymndhng** [comment]
If I am resolving a web path, is it not reasonable to try fetching `http://localhost:8080/raml/docs/getting_started.txt`?

**Comment by kevinrenskers** [comment]
raml2html doesn't do the actual RAML parsing, [https://github.com/raml-org/raml-js-parser](raml-js-parser) does. So you'd have to ask them to change the base path when a remote url is used, so that relative paths within your main raml files work. 

It's not a thing that raml2html does or will ever do.

**Comment by kevinduffey** [comment]
I wonder if we should move raml2html over to the raml-generator project? I think there have been some additions/changes and going forward I believe that project will be adding RAML 1.0 support. Not sure on this.. just throwing it out there right now.
