### ISSUE TITLE
Add Support for Printing

### ISSUE THREAD

**Issue by mikestowe** [raml2html/raml2html#166]
Modals and Tabs do not print well.  Create a separate style sheet to make it printable

**Comment by mikestowe** [comment]
In Progress

**Comment by dwcramer** [comment]
I did a customization of raml2html a while back that gets rid of the modals. Here's what you get from example.raml: http://www.thingbag.net/example.html
One feature we added that example.raml doesn't exercise was that if you have a multi-sentence method description, it displays the first sentence (up to the 1st period) when the method is collapsed and shows the rest with all the method stuff when you expand it.
Feel free to use any ideas or code. I did the standalone version as a quick hack. We have it integrated into a web site with a bunch of shared css and js, but everything here is using bootstrap like raml2html does. Here's the relevant branch of my fork:
https://github.com/dwcramer/raml2html/tree/ciscoHtmlStandaloneLayout

**Comment by mikestowe** [comment]
Thank you!  Will definitely be checking it out and possibly borrowing some code!

**Comment by jayrajput** [comment]
@mikestowe and @dwcramer - I am also looking at ways on how to make the raml2html output without modal windows and much prettier. By prettier, I want to do these
- Show the Query parameters in a table as done in the php-raml2html
- Hide the schema and make it available only on demand (button or link to show the schema). Something like what API-console does it.
- Show only one resource at a time and hide others.
- Show a always visible navigation bar as already done by the raml2html
- Have two sections in the navigation bar. One for the usage and another for the resources.

If things things are already done in some examples, I will be happy to look at the code and may be borrow that code for my changes.

@mikestowe  - I also see that you are the creator for the php-raml2html. Are you planning to enhance the raml2html or make more changes to the php-raml2html project?

One advantage of the raml2html is that you can create a single html file which then can be sent around acting as a offline documentation. Also the raml2html is only a build time tool so it also does not need to be shipped with your product. I am not sure if you can do that with the php-raml2html.

**Comment by jarl-dk** [comment]
:+1:  I would love this as well.

**Comment by mikestowe** [comment]
@jayrajput for the initial changes not planning on changing anything in regards to the screen appearance of raml2html, rather just implementing some hidden elements with a print style sheet to clean up the look and feel when printed. I have a rough draft done, just need to implement in with some merged changes and changes for RAML 1.0

In regards to the future of the raml2html project, I don't see a lot of overlap/ competition between the two projects. I think each serves a distinct need and audience. 

My hope is that as both projects advance, they can continue to enhance each other (i.e. Syntax highlighting, try it now from the PHP project, 1.0 support and others from this).  But I definitely don't see either project being stalled, or replacing the other (as I think that would be detrimental to the goals and focuses of each project as well as their large respective audiences).

**Comment by jayrajput** [comment]
Thanks Michael for the response.

**Comment by kevinrenskers** [comment]
Closing this as work is starting on raml2html 3.0 which will include a brand new modal-less template that should be easier to print. I'll make sure to include a print css as well :)
