### ISSUE TITLE
Allow disabling expanding $ref properties in schemas

### ISSUE THREAD

**Issue by schmkr** [raml2html/raml2html#170]
As mentioned in #169, when trying to expand schemas $ref properties, it might fail when the id property refers to an url but that url does not really exist. 

It would be nice to have an option to disable $ref expanding (and I'll create a separate issue for supplying a fakeroot as suggested in PR comment).

**Comment by nickveenhof** [comment]
This should also be in the raml-jsonschema-expander. Or we need to make raml-jsonschema-expander more fail-safe. Please open an issue there and provide examples how we can test this

**Comment by kevinrenskers** [comment]
Closing this, going to create a new umbrella-issue for all things $ref.
