### ISSUE TITLE
Allow defining a fakeroot for schema $ref expanding

### ISSUE THREAD

**Issue by schmkr** [raml2html/raml2html#171]
When trying to expand schemas $ref properties, it might fail when the id property refers to an url but that url does not really exist (see #169).

Package [refaker](https://github.com/json-schema-faker/refaker) helps resolving schemas while not actually downloading references.  Would be nice to integrate such a thing in this (or actually in [raml-jsonschema-expander](https://github.com/br-adam-newman/raml-jsonschema-expander) I guess).

**Comment by nickveenhof** [comment]
I actually really like this suggestion as it is the only one that really makes sense according to the specification. I'll try to get my hands dirty when I get some time

**Comment by kevinrenskers** [comment]
Closing this, going to create a new umbrella-issue for all things $ref.
