### ISSUE TITLE
Support "Try it" Button in "Request" page.

### ISSUE THREAD

**Issue by ryanemax** [raml2html/raml2html#172]
Support "Try it" Button in "Request" page.
Then the project will be easy to test.

**Comment by kevinrenskers** [comment]
I can't speak for @mikestowe, the new maintainer, but I doubt this will happen. That turns the project from a simple html page generator to something else completely. It's not in the scope of raml2html.

**Comment by mikestowe** [comment]
Exploring options on this, but with OAuth this gets pretty tricky.

**Comment by sichvoge** [comment]
I do agree to @kevinrenskers; the beauty of this project is its simplistic approach. Using that, everyone can simply generate documentation for other formats w/o any efforts.

**Comment by kevinrenskers** [comment]
Yep sorry, it's just not in the scope of a simple documentation generator.
