### ISSUE TITLE
Response tab is not selected if there is no request tab

### ISSUE THREAD

**Issue by ryanpitt** [raml2html/raml2html#174]
Appears in the default template.

To reproduce: Specify a resource with a description and some responses, but do not specify anything to do with the request (no request body, no parameters, and so on). Generate and open the HTML document, and open the modal dialog for that resource. You will see an empty box with a response tab that is not selected. You have to select the tab manually.

Observed in Firefox with a local file, but this probably happens in any browser.

**Comment by truckingsim** [comment]
Can confirm this also happens in chrome.
