### ISSUE TITLE
Template not found when using -t argument

### ISSUE THREAD

**Issue by fireantology** [raml2html/raml2html#177]
Hi,
When executing the raml2html from command line and passing a custom template with -t for example:

`raml2html -t /home/user/mytpl.tpl`

It will give template not found error when executing the command from a directory that is not a parent dir.
I suppose this is due to the way `raml2html.getDefaultConfig` method is called in the bin raml2html.
In fact the value of the argument -t is passed to the `getDefaultConfig` as`templateName` but than the variable `templatesPath`is left to null and the nunjucks library will set to the current directory of execution.
This explain why this is working only if you execute the command from a parent directory.
Tested on windows.

I suppose an easy solution would be to modify the bin so that when a parameter -t is passed than he will set as templatePath the parent directory of the template file.

Thanks for the great code.

**Comment by fireantology** [comment]
If you agree with my solution, I could create a pull request.
Thanks

**Comment by kevinrenskers** [comment]
Can you write up a simple scenario that breaks? Like in which folder are the templates, where is raml2html installed and from where are you running the CLI.

**Comment by fireantology** [comment]
Ok, I will do it as soon as I can

**Comment by kevinrenskers** [comment]
Closing due to lack of response & information.
