### ISSUE TITLE
RAML version support

### ISSUE THREAD

**Issue by ducin** [raml2html/raml2html#179]
Hello,

I know it's related to #156. I just want to ask 2 things:
* where is the `raml2html` support for RAML 1.0 going on - in `raml2html` or `raml-js-parser` or maybe somewhere else?
* could you please extend the `raml2html` markdown docs with the status of RAML version support? As for me, it's difficult that RAML.org recommends to use 1.0, whereas no raml-based tools state whether they support it or not. Checking it by hand costs. What I would appreciate would just be something like below. I think more people would appreciate it.

--

## RAML version support

Currently RAML version 0.8 is fully supported. If you want to use RAML 1.0, you might use a temporary overcome (see #156) or help to implement this feature in #?.

**Comment by sichvoge** [comment]
That is a pretty nice idea. Could you add a PR for that?

**Comment by ducin** [comment]
Do you want this PR to be aimed at **develop or master branch**? In _contrubition_ section it's stated to submit PR code to develop, but in fact it's not code - it's readme.

**Comment by sichvoge** [comment]
I'd still follow the contribution section even with a little change like that. BTW, there is a `raml1.0` branch now and as soon as my PR gets merged into raml2obj; we'll update the raml2html `raml1.0` branch.

**Comment by ducin** [comment]
But when this readme update gets into master, it'd get obsolete because of 1.0 support... at least this is how I udnerstand it.

The whole poinf of my issue is that when I find this repo, I get to the default branch which is `master` here. Nobody goes through readmes of other branches and PR-ing this to develop doesn't help newcomers  IMHO.

**Comment by kevinrenskers** [comment]
I'd add the readme change to the master branch, for the reasons you gave.

**Comment by sichvoge** [comment]
@ducin, I just inidcated that I'd follow the contribution guide which explicitly mentioned that any contribution is via PR and the `develop` branch which will be reviewed and merged into `master`. I was not saying it will stay in a branch ;)

But if @kevinrenskers is fine to directly change that inside the `master`, so be it.

**Comment by kevinrenskers** [comment]
@sichvoge if there are other changes in the develop branch it'll be too much trouble to then merge it to master. Easier in this case to create the PR to the master branch and then merge that back to develop. But yes, in normal cases, definitely to develop :)

**Comment by sichvoge** [comment]
I am closing that as this was done! Thanks for contribution.
