### ISSUE TITLE
Can not install raml2html

### ISSUE THREAD

**Issue by agsmorodin** [raml2html/raml2html#183]
Hi,

I am trying to install the latest version and get the following error:

`npm i -g raml2html
npm WARN deprecated native-or-bluebird@1.2.0: please use 'any-promise' instead
npm WARN engine address@1.0.0: wanted: {"node":">= 0.12.0"} (current: {"node":"0.10.32","npm":"2.1.10"})
npm WARN optional dep failed, continuing fsevents@1.0.8
npm WARN engine is-buffer@1.1.3: wanted: {"node":">=0.12"} (current: {"node":"0.10.32","npm":"2.1.10"})
/opt/node/bin/raml2html -> /opt/node/lib/node_modules/raml2html/bin/raml2html
npm ERR! Linux 3.10.0-229.el7.x86_64
npm ERR! argv "node" "/opt/node/bin/npm" "i" "-g" "raml2html"
npm ERR! node v0.10.32
npm ERR! npm  v2.1.10
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package nunjucks does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer nunjucks-markdown@1.0.0 wants nunjucks@^1.1.0

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/npm-debug.log`

At the same time this command '/opt/node/bin/npm  install -g raml2html@2.2.0' works perfectly.

**Comment by kevinrenskers** [comment]
Arg crap, the new version of `nunjucks-markdown` is broken but apparently the old one doesn't want to play with the new version of nunjucks. Even though it does work perfectly fine :/

I'll take a look tonight, unless someone beats me to it. Sorry for the inconvenience.

**Comment by kevinrenskers** [comment]
Pushed 2.4.0
