### ISSUE TITLE
Usage: command line script error

### ISSUE THREAD

**Issue by AlexVentura** [raml2html/raml2html#184]
I'm working with versions below and it fails when converting to HTML using both commands:

`raml2html api_doc.raml > assets/index.html`
`raml2html --input api_doc.ram --output assets/index.html`

**npm** version: 3.7.3
**raml2html** version: 2.4.0
**raml** version: 0.8

I got the next error:

`[Error: TypeError: Cannot read property 'indexOf' of null]`

Then I uninstall that version and downgrade to version **`2.3.0`** and it was the same, not working!
Then I uninstall that version and downgrade to version **`2.2.0`** and ***it seems to work fine!***

2.2.0 fix the problem!

**Comment by kevinrenskers** [comment]
It works fine for the example raml files in the repo, so I might need your raml file to reproduce the error. You can email it to kevin@mixedcase.nl if you don't want it on github :)

**Comment by kevinrenskers** [comment]
It's the call to `ramljsonexpander.expandJsonSchemas` that results in an error. I think you should create a new ticket for https://github.com/br-adam-newman/raml-jsonschema-expander with your RAML file, so that they can solve this bug.

**Comment by AlexVentura** [comment]
Alright, I will do so.
Thanks in advance!
