### ISSUE TITLE
Seems not to read resourceTypes headers and query parameters

### ISSUE THREAD

**Issue by alexresta** [raml2html/raml2html#188]
When defining traits and resource types in included raml files, then they don't show in the generated HTML, as if it didn't have query parameters. 

in my raml, for example I have this:

```
catalog:
  type: collection
  get:
    description: DESC
    responses:
      200:
        body:
          application/json:
            schema: !include schemas/catalog-schema.jschema
            example: !include examples/catalog-example.json
```

the type: collection is defined in a separate raml:

resourceTypes: !include foundation/resource-types.raml

**resource-types.raml**
```
- collection:
    is: [secured]
    get?:
      is: [filterable, pageable]
      responses:
        200:
          body:
            application/json:
```

    
pageable is included in traits.raml:

traits: !include foundation/traits.raml

**traits.raml:**
```
- pageable:
    queryParameters:
      page:
        description: Page number to be retrieved.
        type: integer
        minimum: 1
        required: false
      size:
        description: The amount of items a page can contain.
        type: integer
        minimum: 1
        required: false
```

**Comment by alexresta** [comment]
Sorry for the bad styiling, i'll sort it out later...

**Comment by nmors** [comment]
That's strange.. It works for me!

However, I am including my resourceTypes a little differently, please try this way and let me know if it works:

``` RAML
resourceTypes:
  - collection-item: !include resourceTypes/collection-item.raml
  - collection: !include resourceTypes/collection.raml
  - configuration: !include resourceTypes/configuration.raml
  - data-export: !include resourceTypes/data-export.raml
  - meta-data: !include resourceTypes/meta-data.raml
  - run-job: !include resourceTypes/run-job.raml
```

**Comment by alexresta** [comment]
ok! I found out what happens. The thing is that if you define optional properties it doesn't print it its traits. This is useful for example when defining resources that are a same type but some can receive POST and not others.

Seems that optional operations is working for POST, but not for GET. Let me explain:

Using this declaration in main RAML:
resourceTypes:
  - collection: !include resourceTypes/collection.raml

/items:
  type: collection
  description: |
    Retrieves current set of items from the catalog.

    *Please note around 300k items available*
  get:
    responses:
      200:
        body:
          application/json:
            schema: !include schemas/items-schema.jschema
            example: !include examples/items-example.json

  post:
    responses:
      200:



This version of collection.raml does not print the traits in the html for the GET, but does for the POST (notice the ? after get):

is: [secured]
post?:
  body:
    application/json:
  responses:
    200?:
  
get?:
  is: [filterable, pageable]
  responses:
    200:
      body:
        application/json:

This version (without ?)  does print the traits in the html, for the GET, but forces all collections to have a GET operation:
is: [secured]
post?:
  body:
    application/json:
  responses:
    200?:
  
get:
  is: [filterable, pageable]
  responses:
    200:
      body:
        application/json:

**Comment by alexresta** [comment]
Here a full example I prepared, and I zipped it with also the generated HTML:

#%RAML 0.8
title: test1
version: v1.0
baseUri: http://localhost

traits:
  - secured:
      headers:
        Authorization:
          description: Used to send a valid OAuth access token.
          type: string
          required: true
          example: Bearer xxxxxxxxxxxxxxxx

  - date-filterable:
      queryParameters:
        startdate:
          type: string
          required: false
        enddate:
          type: string
          required: false

resourceTypes:
  - collection:
      is: [secured]
      post?:
        body:
          application/json:
        responses:
          200?:
            description: Returned if the object was retrieved successful.
          401?:
            description: Returned if the calling user is not authenticated.
      get?:
        is: [date-filterable]
        responses:
          200:
            body:
              application/json:
          400?:
            description: Returned if the the request is invalid.
  - collection2:
      is: [secured]
      post?:
        body:
          application/json:
        responses:
          200?:
            description: Returned if the object was retrieved successful.
          401?:
            description: Returned if the calling user is not authenticated.
      get:
        is: [date-filterable]
        responses:
          200:
            body:
              application/json:
          400?:
            description: Returned if the the request is invalid.


/items:
  type: collection
  description: I should have a GET request, and a POST request, but GET is not showing REQUEST
  get:
    responses:
      200:
        body:
          application/json:

  post:
    responses:
      200:

/item2:
  type: collection2
  description: I should have only a GET request, and it's OK
  get:
    responses:
      200:
        body:
          application/json:
/item31:
  type: collection
  description: I should have only a GET request, but not showing
  get:
    responses:
      200:
        body:
          application/json:
/item32:
  type: collection
  description: I should have only a POST request
  post:
    responses:
      200:


[apiexample.zip](https://github.com/raml2html/raml2html/files/197142/apiexample.zip)

**Comment by alexresta** [comment]
Well, I checked and tried directly raml-js-parser and I think it's a bug in that module, so.. not a lot of options here, I guess.

**Comment by alexresta** [comment]
Hi! I submitted the bug and it got fixed. I guess we need to wait to be included in a release?

https://github.com/raml-org/raml-js-parser/issues/174

**Comment by alexresta** [comment]
aaand it's released.. thanks!

https://github.com/raml-org/raml-js-parser/releases

**Comment by Rotzbua** [comment]
@alexresta Hi, does it now work for you? Because I still have the bug, but I have the latest version of `raml-js-parser`. Did you found a other solution?
