### ISSUE TITLE
RAML1.0 Does not Appear to be Working in Feature Branch

### ISSUE THREAD

**Issue by hjc1710** [raml2html/raml2html#191]
Hey! So, I know RAML 1.0 is experimental and you guys are working on it, but we'd really love to start using it (those data types!), so I decided I'd try out the feature branch and see if it worked with our existing RAML.

Unfortunately... it did not. I then tried the new feature branch with a much more simplified RAML and it... also did not work :cry:.

Here is what I did:

```sh
$ npm uninstall raml2html
$ npm install raml2html/raml2html#raml1.0
$ ./node_modules/.bin/raml2html x.raml | less
```

For `x.raml` I tried a number of examples. You can see all of them [here](https://gist.github.com/hjc1710/c5db1bf62cceb7fac3456dbf7df51cb5). The first is a very simple schema I whipped up by hand, that does successfully compile with the current latest `raml2html` release on npm. The second two are examples ripped from the ["What's New in RAML 1.0?"](http://raml.org/developers/whats-new-raml-10) blog post and require RAML 1.0, so I can't test them with the current release of `raml2html`.

All of them failed with just this error: 

```
[Error: Error: Api contains errors.]
```

More than happy to provide any other info you might need, just let me know!

Versions report:

```sh
$ npm --version
3.4.0
$ node --version
v4.2.2
```

OS: Linux (Ubuntu)

**Comment by sichvoge** [comment]
Can you try to clone the `raml1.0` branch and simple execute `npm install` and run `examples/raml1.0/script.js`?

Its working for me and just want to make sure that I don't miss something. You know how developer are: "Its working on my computer" :D

**Comment by gavares** [comment]
I'm having the same problem as @hjc1710. I ran the `scripts.js` file as @sichvoge asked above:

```shell
( raml1.0 U) 11:27:49 ggavares/workspace/raml2html > ./examples/raml1.0/script.js
1:  54628
( raml1.0 U) 11:27:51 ggavares/workspace/raml2html >
```

**Comment by hjc1710** [comment]
### NOTE: This is long, skip to the bottom for a TL;DR

@sichvoge - certainly! I can of course do that for you!

Executing that script and looking at what it does, it looks like it works:

```
hayden[beard-machine] {~/gits} ~> git clone https://github.com/raml2html/raml2html.git
Cloning into 'raml2html'...
remote: Counting objects: 1480, done.
remote: Total 1480 (delta 0), reused 0 (delta 0), pack-reused 1479
Receiving objects: 100% (1480/1480), 1.59 MiB, done.
Resolving deltas: 100% (803/803), done.
hayden[beard-machine] {~/gits} ~> cd raml2html/
hayden[beard-machine] {~/gits/raml2html} (master) ~> git fetch origin raml1.0:raml1.0
From https://github.com/raml2html/raml2html
 * [new branch]      raml1.0    -> raml1.0
hayden[beard-machine] {~/gits/raml2html} (master) ~> git checkout raml1.0 
Switched to branch 'raml1.0'
hayden[beard-machine] {~/gits/raml2html} (raml1.0) ~> git pull origin raml1.0 
From https://github.com/raml2html/raml2html
 * branch            raml1.0    -> FETCH_HEAD
Already up-to-date.
hayden[beard-machine] {~/gits/raml2html} (raml1.0) ~> npm install
# output omitted for sanity's sake
hayden[beard-machine] {~/gits/raml2html} (raml1.0) ~> node examples/raml1.0/script.js 
1:  54628
```

Since it looks like the goal of that script is to render something and print the content length, so that seems in order.

Working off of that example, I moved my example RAML docs into the `examples/raml1.0` file, made some edits to `script.js` and ran it again, with the following results:

```sh
hayden[beard-machine] {~/gits/raml2html} (raml1.0) ~> mv annotations.raml examples/raml1.0/
hayden[beard-machine] {~/gits/raml2html} (raml1.0) ~> mv types.raml examples/raml1.0/
hayden[beard-machine] {~/gits/raml2html} (raml1.0) ~> mv simple.raml examples/raml1.0/
hayden[beard-machine] {~/gits/raml2html} (raml1.0) ~> cd examples/raml1.0/
hayden[beard-machine] {~/gits/raml2html/examples/raml1.0} (raml1.0) ~> vim script.js  # let's parse simple.raml
hayden[beard-machine] {~/gits/raml2html/examples/raml1.0} (raml1.0) ~> node script.js 
error!  { [Error: Api contains errors.]
  parserErrors: 
   [ { code: 7,
       message: 'Can not parse JSON:Unexpected token E',
       path: 'simple.raml',
       start: 309,
       end: 316,
       line: 16,
       column: 14,
       range: [Object],
       isWarning: true } ] }
hayden[beard-machine] {~/gits/raml2html/examples/raml1.0} (raml1.0) ~> vim script.js  # let's try types.raml
hayden[beard-machine] {~/gits/raml2html/examples/raml1.0} (raml1.0) ~> node script.js 

# See here for the output: https://gist.github.com/hjc1710/13a73d9f8b5dde435f5642237bdfda44

hayden[beard-machine] {~/gits/raml2html/examples/raml1.0} (raml1.0) ~> vim script.js  # finally, annotations.raml
hayden[beard-machine] {~/gits/raml2html/examples/raml1.0} (raml1.0) ~> node script.js 
error!  { [Error: Api contains errors.]
  parserErrors: 
   [ { code: 2,
       message: 'Unknown node: parameters',
       path: 'annotations.raml',
       start: 254,
       end: 264,
       line: 9,
       column: 4,
       range: [Object],
       isWarning: false },
     { code: 2,
       message: 'Unknown node: parameters',
       path: 'annotations.raml',
       start: 305,
       end: 315,
       line: 12,
       column: 4,
       range: [Object],
       isWarning: false },
     { code: 2,
       message: 'Unknown node: parameters',
       path: 'annotations.raml',
       start: 350,
       end: 360,
       line: 15,
       column: 4,
       range: [Object],
       isWarning: false },
     { code: 2,
       message: 'Unknown node: parameters',
       path: 'annotations.raml',
       start: 404,
       end: 414,
       line: 18,
       column: 4,
       range: [Object],
       isWarning: false },
     { code: 4,
       message: 'Response property already used: \'(assertion)\'',
       path: 'annotations.raml',
       start: 823,
       end: 834,
       line: 39,
       column: 8,
       range: [Object],
       isWarning: false },
     { code: 4,
       message: 'Response property already used: \'(assertion)\'',
       path: 'annotations.raml',
       start: 856,
       end: 867,
       line: 40,
       column: 8,
       range: [Object],
       isWarning: false } ] }
```

Where the three RAML files referenced are in [this version of the gist](https://gist.github.com/hjc1710/c5db1bf62cceb7fac3456dbf7df51cb5/05052cd0560218cc2a9c7235bc1fdb90ef37c87a) and the file names match up. The only thing I did in each of the `vim script.js` commands was edit line 12 to point to the relevant RAML file at the time.

I tinkered with `simple.raml` a bit which is when I realized... the `simple.raml` in that gist is no longer valid! I wasn't aware that they changed the structure of responses so heavily and that types were now ingrained in them. So, that one's on me and shouldn't pass at all. However, this then got me thinking. While this is invalid in RAML 1.0, it's still valid in RAML 0.8, so I changed the RAML type to 0.8 and got this error:

```
hayden[beard-machine] {~/gits/raml2html/examples/raml1.0} (raml1.0) ~> cat simple.raml | head -1
#%RAML 0.8
hayden[beard-machine] {~/gits/raml2html/examples/raml1.0} (raml1.0) ~> node script.js 
error!  { [Error: Api contains errors.]
  parserErrors: 
   [ { code: 7,
       message: 'Can not parse JSON:Unexpected token E',
       path: 'simple.raml',
       start: 309,
       end: 316,
       line: 16,
       column: 14,
       range: [Object],
       isWarning: true } ] }
```

The rest of `simple.raml` is as it is in the gist. Given that there's nothing in there requiring version 1.0 (in `script.js`), I think this might have broken BC with RAML 0.8.

So, since that was changed heavily, I decided to re-grab my RAML 1.0 examples, which are now updated in [the gist](https://gist.github.com/hjc1710/c5db1bf62cceb7fac3456dbf7df51cb5). This changed the type one, which now passes:

```
hayden[beard-machine] {~/gits/raml2html/examples/raml1.0} (raml1.0) ~> vim script.js  # make this types.raml
hayden[beard-machine] {~/gits/raml2html/examples/raml1.0} (raml1.0) ~> node script.js 
1:  6880
```

Unfortunately, looks like the Annotations one isn't different and it's still failing:

```
hayden[beard-machine] {~/gits/raml2html/examples/raml1.0} (raml1.0) ~> vim script.js  # let's try annotations.raml
hayden[beard-machine] {~/gits/raml2html/examples/raml1.0} (raml1.0) ~> node script.js 
error!  { [Error: Api contains errors.]
  parserErrors: 
   [ { code: 4,
       message: 'Response property already used: \'(assertion)\'',
       path: 'annotations.raml',
       start: 896,
       end: 907,
       line: 35,
       column: 8,
       range: [Object],
       isWarning: false },
     { code: 4,
       message: 'Response property already used: \'(assertion)\'',
       path: 'annotations.raml',
       start: 929,
       end: 940,
       line: 36,
       column: 8,
       range: [Object],
       isWarning: false } ] }
```

But, that might be on the raml2obj guys. So, I poked in even further since that error was rather interesting. If we try one of their [other examples](https://github.com/raml-org/raml-spec/blob/raml-10/versions/raml-10/raml-10.md/#applying-annotations) then it renders fine!

```
hayden[beard-machine] {~/gits/raml2html/examples/raml1.0} (raml1.0) ~> cat annotations.raml 
#%RAML 1.0
title: Illustrating allowed targets
mediaType: application/json
annotationTypes:
  meta-resource-method:
    allowedTargets: [ Resource, Method ]
  meta-data:
    allowedTargets: TypeDeclaration
types:
  User:
    type: object
    (meta-data): on an object; on a data type declaration
    properties:
      name:
        type: string
        (meta-data): on a string property
/users:
  (meta-resource-method): on a resource
  get:
    (meta-resource-method): on a method
    responses:
      200:
        body:
          type: User[]
          (meta-data): on a body
hayden[beard-machine] {~/gits/raml2html/examples/raml1.0} (raml1.0) ~> node script.js 
1:  6589
```

So, it looks like our error is with the `allowMultiple: True` key, which should allow repeated keys (how this works in YAML is beyond me, but YAML is madness).

SO! Sorry for that wall of text, but I think there's some good info in there. 

### A summary:

- Looks like rendering RAML0.8 is now broken. I confirmed this with both `script.js` and `bin/raml2html`:
    ```
    hayden[beard-machine] {~/gits/raml2html/examples/raml1.0} (raml1.0) ~> ../../bin/raml2html simple.raml 
    [Error: Error: Api contains errors.]
    ```
- Looks like the `allowMultiple: True` key isn't working for annotations (we're getting a duplicate key error for that). Everything else is working fine.
- I totally misunderstood the new `responses` section for RAML1.0, so of course my original documents won't compile, and never will, that's on me.

So, looks like my original bug report is wrong, but I think I did discover two, other, unrelated bugs with BC and `allowMultiple`. I think the issue title should be changed, but I'll leave that to you.

Lemme know if you have other questions @sichvoge!

**Comment by sichvoge** [comment]
First thanks all for testing an reporting ;)

1)

@hjc1710 & @gavares the `script.js` file is producing a `example.html` file in the same repository that contains the HTML output of your RAML.

2) 

@hjc1710 RAML annotations has been changed with RC2 to not use the `parameter` node anymore, and also `allowMultiple` is not supported anymore as well since that violates rules in YAML not having multiple keys with the same name. I uploaded a modified example [here](https://github.com/raml-org/raml-examples/blob/master/annotations/simple-annotations.raml). If you take that file everything is working fine and the `script.js` produces the correct HTML file. 

3) 

The `simple.raml` contains an example that is not a valid JSON. The new parser checks for these kind of things and is more strict than the old. The strictness of the new will avoid mistakes in any JSON or any other structural/reference problems that might not be easily found with the old. Basically, you already get compile time validation instead of realising that something does not work at runtime.

4) 

The `types.raml` also has some mistakes that got fixed in RC2. Please see [here](https://github.com/raml-org/raml-examples/blob/master/typesystem/complex.raml)

With these changes you should be able to run fine. I tried all the different examples that you published. Let me know if you have any other question.

**Comment by hjc1710** [comment]
@sichvoge - ahhhhhhhhhhhh, it's all due to me misunderstanding RAML 1.0! I had no idea there was an RC2 even in the works, let alone something I could look at. I assume [this](https://github.com/raml-org/raml-spec/blob/raml-10-rc2/versions/raml-10/raml-10.md) is the proper RC2 spec?

I was wondering how `allowMultiple` would even work from a YAML perspective. Makes sense that that needed axing...

I really appreciate you adding those examples to the `raml-org/raml-examples` repo, that's going to be **super** helpful for me as I transition. I grabbed all of those examples and ran them through the `raml1.0` branch locally and can confirm that they do compile successfully. Thanks!

So, since compile time validation is new with this branch, will this result in a major version bump? I imagine it should, since it will likely break a lot of people's existing RAML 0.8 files (I know for some of my examples, they aren't valid JSON and are a short descriptive string). Also, is compile time validation *always* required? Some of my routes are download routes and return binary responses, so a JSON response isn't valid and I like to throw something along the lines of: "Binary response returned." in the example section. Is this still something I can do?

Also, how do I access the annotations with custom nunjucks templates? I know I can do a TON with that and really make our documentation awesome.

Thanks so much for helping me!

**Comment by sichvoge** [comment]
> So, since compile time validation is new with this branch, will this result in a major version bump?

Non of the existing RAML 0.8 files should be effected on the changes as well; if they are there is a bug with the parser probably. The upgrade from 0.8 and 1.0 is different since there are breaking changes. We tried to minimize them as much as possible, but there will be. In terms of major version for raml2html, guess it will be. When I updated raml2obj and run `npm version` it went directly up one major version. That will potential the same here :)

> Also, how do I access the annotations with custom nunjucks templates?

Good question, that is something I need to find out as well. Some people asked me to have a `tag` annotation so that you can show them in documentation tools like raml2html. So maybe you tag a resource or api as `deprecated` or something else.

BTW, the raml-examples repository includes samples for RC2. Please bear in mind that RC2 is not fully released and the parser does not fully cover them yet. ;)

**Comment by moorhsurc** [comment]
@sichvoge, per your instructions (https://github.com/raml2html/raml2html/issues/191#issuecomment-209012453) it works on my machine too :)

output is: `1:  54628` and 54628 is the size of the generated example.html.

**Comment by kevinrenskers** [comment]
So I guess this issue can be closed? If not please reply and I'll reopen :)
