### ISSUE TITLE
Backward compatibility - Handlebars.js

### ISSUE THREAD

**Issue by sdomagala** [raml2html/raml2html#193]
Hello,
I have pretty big templates written in handlebars.js that would be hard to port to nunjucks, and old version of raml2html causes dependency issues with other RAML packages so I'd have to update it.

Is there a way to still use `handlebars` after migrating from 1.6.0? 

Cheers :)

**Comment by kevinrenskers** [comment]
Yes, you can use raml2html as a library and provide your own config object with your own `processRamlObj` function. See readme & examples.
