### ISSUE TITLE
Resolve $ref in JSON schemas

### ISSUE THREAD

**Issue by raafael911** [raml2html/raml2html#199]
First of all thanks for the great tool, it is becoming a fundamental part in our daily work.
In this feature request I want to encourage you to make it possible that `$ref` properties in JSON schema are resolved and substituted by the definition they point to. This would make the schemas section in the generated HTML much more readable.

**Comment by gpessa** [comment]
+1

**Comment by kevinrenskers** [comment]
Closing this, going to create a new umbrella-issue for all things $ref.
