### ISSUE TITLE
Regression: usage of raml-json-expander breaks {$ref: #subschema} case

### ISSUE THREAD

**Issue by arty-name** [raml2html/raml2html#201]
We are using RAML with JSON Schema with definitions to avoid duplication. As an example: we have a lot of entries like this: `"scope": {"$ref": "#/definitions/scope"}` where the part `"#/definitions/scope"` point to the other section of the same file. This is called [inline dereferencing](http://json-schema.org/latest/json-schema-core.html#anchor30). 

`raml2html@2.3.0` introduced `raml-jsonschema-expander` to expand the referenced schemas. [However the author of the module says it is not designed for inline dereferencing](https://github.com/br-adam-newman/raml-jsonschema-expander/issues/3#issuecomment-218260149). As a result we cannot use raml2html@2.3.0+, because raml-jsonschema-expander throws an error for our schemas: 

```
Error: Error: ENOENT: no such file or directory, open '/#/definitions/scope'
```

So a perfectly valid schema was working previously, but is no longer supported. What would be the best way to resolve this issue?

**Comment by kevinrenskers** [comment]
raml2html 4 (currently in beta) got rid of raml-jsonschema-expander because there are too many problems and feels like an unfinished implementation with too many feature requests still open. We'll revisit the whole schema rendering later once RAML 1 support is done.

**Comment by kevinrenskers** [comment]
So I would advise you to switch to raml2html 4 now (you'll need to switch to the RAML 1 format though). Sorry I don't have another solution :(
