### ISSUE TITLE
Display union types in RAML 1.0

### ISSUE THREAD

**Issue by sichvoge** [raml2html/raml2html#203]
RAML Version: 1.0
Branch: raml1.0

Currently, the raml1.0 branch contains a first implementation of displaying types. The basic of it is, that the template gets all the different properties and displays them without any type information (name of the type etc.). Gathering properties does in most cases work, but not for union types.

Lets discuss whats the best way is to display types in general and special cases like union types. Does anyone have a good idea?

**Comment by kevinrenskers** [comment]
Closing this since we'll work on the new templates soon with RAML 1.0 support (and the raml1.0 branch is gone anyway).
