### ISSUE TITLE
Types from libraries are not getting displayed

### ISSUE THREAD

**Issue by sichvoge** [raml2html/raml2html#205]
RAML Version: 1.0
Branch: raml1.0

Types that are defined inside a library are not displayed yet. Instead you get an error inside the template.

@ivokh can you have a look on that?

**Comment by ivokh** [comment]
I don't get an error. The library content is not parsed so its content is not added to the ramlObj. A reference is added to the ramlObj so it should be possible to parse the library as well and combine the results.
I'm wondering if this is not the responsibility of the raml2obj library. If this is not the case I could try to implement this.

**Comment by amammes** [comment]
@ivokh, what parser version did you use? I get template errors with the most simple library test cases.

**Comment by ivokh** [comment]
I did just a clone, move to branch raml1.0 and npm install. Got parser version 0.8.18. I thought I had the same problem before my last try. To test for the issue I created a separate file with the user type. Removed it from the example.raml file, included the library and changed the reference to the User type. 
After this running the examples script gave no errors but the /account/users didn't inherit the User properties.

**Comment by amammes** [comment]
I was trying to strip down my RAML with libraries as much as possible, trying to get to the point where I do not get a template error. However, I've reached the point where I removed the libraries and am still getting template error. Sorry but I don't understand what I am doing wrong, since api-workbench does not mark any errors. Could you help me?
```
#%RAML 1.0
title: Example RAML 1.0
version: 1
baseUri: http://example.com/{version}
mediaType: application/json

/:
  get:
    responses:
      200:
        body:
          type: string[]
          example: ["1","2"]
```

Error is:
```
error!  { [Template render error: (C:\Users\Axel\Documents\IFSF\raml2html\raml2html\lib\template.nunjucks)
  Template render error: (C:\Users\Axel\Documents\IFSF\raml2html\raml2html\lib\resource.nunjucks) [Line 206, Column 53]
  TypeError: Cannot read property 'length' of undefined] name: 'Template render error' }
```

**Comment by kevinrenskers** [comment]
Let's close this, as raml2html will get new templates and proper RAML 1 support with raml2obj 4.x.
