### ISSUE TITLE
Scalar types are not displayed

### ISSUE THREAD

**Issue by sichvoge** [raml2html/raml2html#206]
RAML Version: 1.0
Branch: raml1.0

If you have a body that defines its content as a scalar type, not object, the scalar type does not get rendered. 

```yaml
#%RAML 1.0
title: API used to test broken features
mediaType: application/json

types:
  myType:
    type: string

/:
  get:
    responses:
      200:
        body:
          type: myType
```

![image](https://cloud.githubusercontent.com/assets/498114/15394442/d485df1e-1dca-11e6-9c07-c2d8daf49865.png)

**Comment by kevinrenskers** [comment]
Types are rendered again in 4.0.0-beta7, and this bug is solved.
