### ISSUE TITLE
Configurable size of the modal

### ISSUE THREAD

**Issue by Alexx-G** [raml2html/raml2html#211]
Is it possible to configure the size of the modal dialog without forking this repository, change size in html and use that fork?

The point is that most of our schemas look pretty annoying in that modal. Changing it's size improves a bit readability of the schema.

**Comment by kevinrenskers** [comment]
No need to fork the repo - you can just use custom templates (use the included ones as the basis). But the next version of raml2html won't have modals anymore so probably easiest to wait for that :)

**Comment by Alexx-G** [comment]
Thanks for the update.
I've checked templates before creating this issue, but I don't remember why exactly it didn't help.

Are you going to replace modals with collapsible sections for endpoint details?

**Comment by sichvoge** [comment]
Maybe [that](https://github.com/raml2html/raml2html/issues/89#issuecomment-105060533) give you a better idea on what we / Kevin tries to achieve with the new template ;)

**Comment by Alexx-G** [comment]
Missed that... Looks nice.
Looking forward to test it. Thanks for your effort!
