### ISSUE TITLE
unhelpful error message `[Error: Error: Api contains errors.]`

### ISSUE THREAD

**Issue by alexch** [raml2html/raml2html#212]
```
$ cat > /tmp/foo.raml
#%RAML 1.0
title: Bogus API
xxx: yyy
$ ./bin/raml2html /tmp/foo.raml
[Error: Error: Api contains errors.]
```

The errors are preserved and attached to the error object -- see line 266 of `node_modules/raml-1-parser/dist/raml1/apiLoader.js`  -- but not displayed on exit. 

May be related to https://github.com/raml2html/raml2html/issues/159

**Comment by alexch** [comment]
sticking a `console.log` in apiLoader.js shows

```
[ { code: 2,
    message: 'Unknown node: xxx',
    path: 'foo.raml',
    start: 28,
    end: 31,
    line: 2,
    column: 0,
    range: [ [Object], [Object] ],
    isWarning: false } ]
```

so raml2html should at least display something like "Unknown node: xxx on foo.raml:2:0"

**Comment by mkn8rd** [comment]
can we merge this already?

**Comment by sichvoge** [comment]
done! you are free to close the issue :)
