### ISSUE TITLE
1.0 doesn't expand 'uses' directive

### ISSUE THREAD

**Issue by beno** [raml2html/raml2html#219]
I have a RAML 1.0 spec that imports its types declarations through a 'uses' property:

    uses:
       common: types/common.raml
       #etc...

When I try to generate this, raml2html(raml1.0) crashes. Investigating the error shows that raml2html expects a 'types' property on the internal ramlObj (which should get populated from the 'uses' directive, but evidently doesn't). Adding a dummy 'types' declaration removes the error, but the types from the 'uses' directive are still ignored.

~~Edit: it appears types are not properly parsed at all? I never see any output from them. Also, inline examples are rendered as just [Object]s, so not very useful.~~

**Comment by sichvoge** [comment]
What do you mean by "not properly parser at all"? And yes there are still some gaps that we need to close and any help to do that is always very appreciated ;) 

Specifically, the libraries topic is hard and I'd be happy to see some ideas what we can do to bring the content into the context.

**Comment by beno** [comment]
Let's take this one at a time, and stick to the originally filed bug. I have amended the post. Thanks.

**Comment by sichvoge** [comment]
Isn't that more a problem for raml2obj to populate information from the library into the JSON obj? That is not done automatically since libraries uses a complete different approach than just inlining stuff (thats why it does not use `!include`). Hence, me saying that the library topic is hard ;)

**Comment by beno** [comment]
Yes, I suppose it is. I have investigated the raml2obj codebase a bit and found that none of the tests or examples deal with 'uses' directives, and there seems to be very little code in there that deals with 'uses'. For instance, on line 216 in builder.js a uses variable gets set, but it's never used anywhere else. Should I report it there?

**Comment by kevinrenskers** [comment]
raml2obj doesn't have a builder.js file, and its [index.js](https://github.com/raml2html/raml2obj/blob/master/index.js) file is only 113 lines long.

**Comment by beno** [comment]
I'm sorry, I meant the raml-1-parser that raml2obj calls.

https://github.com/raml-org/raml-js-parser-2

Somehow I end up with a builder.js file that contains that code.

Frankly, I get the feeling this has become a bit too complex for what we want from it. Shouldn't it be much more straightforward to go from a yaml representation with a bit of logic to a textual/html representation? This seems completely impenetrable to new contributors.

**Comment by sichvoge** [comment]
Hi, I feel your pain. There could be some solutions to the problem, but having libraries is a whole different world as they are not usual includes (that's why you don't use `namespace: !include lib.raml` but instead skip the `!include`) especially with the complexity the type system introduces. Expanding them is much more difficult since you have the notions of unions. Maybe there is a way to abstract the complexity inside the raml2obj project so that you don't have to care about it and I am very open to any ideas.

I know from a source here at Mulesoft, that one would be to add the library items to the resulting parser object (the one that raml2obj uses). Not sure if that is the best idea though. Maybe we add another object to the raml2obj object called `libraries` and basically bring all the different information into it. For example:

```yaml
uses:
  namespace: lib.raml
```

```yaml
#%RAML 1.0 Library

resourceTypes:
  collection:
   item:
```

will translate into:

```json
{
  "libraries": [
    {
      "namespace": [
         {
           "resourceTypes": [
              {
                "collection": { ... },
              },
              {
                "item": { ... }
              }
            ]
          }
        ]
      }       
    ]
}                
```

What do you guys think? Remember, expanding everything might be tricky in the end as well as you might get into a loop when you extend types or traits, or others. So its better to have ALL information inside the same json object.

**Comment by beno** [comment]
I have been working on a simple parser and renderer for RAML 1.0 written in Crystal, and so far am getting pretty good traction with it. Instead of nesting, the way it handles namespaces is to modify the 'keys' when loading libraries and the merge these into the appropriate directive. 

```RAML
uses:
  common: common.raml #let's say this file has an Article type
types:
  Article: #...
```
becomes

```RAML
types:
  Article: #...
  common.Article: #...
```

It works pretty well so far, and this way the naming of the included items and the way they are referenced in the spec are the same. It is quite possible I haven't thought this through far enough, but for now it's doing what I want from it.

**Comment by sichvoge** [comment]
That is one way indeed. I see some problems coming up. For example, what happens when the the type article is using something that has been defined in another library?

(BTW, the API Console from Mulesoft currently uses the same approach)

**Comment by sichvoge** [comment]
Can you share your repo so I can have a look on what you have build so far :)

**Comment by beno** [comment]
Sure, let me clean it up a bit and I'll share.

**Comment by sichvoge** [comment]
How do you solve that?

> For example, what happens when the type common.Article is using something that has been defined in another library?

**Comment by beno** [comment]
Not entirely sure what you mean, but files are loaded recursively, so they all get parsed the same way, regardless if it’s the main spec or a imported library. So in the end I end up with a single API object that aggregates and namespaces all specs as described. Of course when a spec depends on something external those files need to be present and readable.

I will post my code tonight so you can take a look.

Brgds,
Michel

**Comment by beno** [comment]
Take a look: https://github.com/beno/ramlrenderer

It's a partial implementation, barely under test, so be careful. Blazing fast though :)

**Comment by beno** [comment]
Hi @sichvoge, I am almost finished working through my roadmap. Can I please ask you to take a [look](https://github.com/beno/ramlrenderer) at what I have so far and see what happens when you run some RAML through it?

**Comment by sichvoge** [comment]
@beno sure, does that have time till next week (beginning). extremely busy right now :)

**Comment by beno** [comment]
But of course, no rush. I have some other refinements to work on in the mean time, but I believe the bulk is done.

**Comment by kevinrenskers** [comment]
raml2obj 4.0.0-beta2 (with raml-1-parser 1.1.3) should support libraries just fine - there are unit tests that deal with `uses`.

The new raml2html version will use the new raml2obj with brand new templates so I think this ticket can be closed.
