### ISSUE TITLE
1.0 crashes on write to file

### ISSUE THREAD

**Issue by beno** [raml2html/raml2html#220]
Whenever I generate a html string it works fine when outputting to console, but there's a crash when I either use the -o output option, or when I send the result to a file from the command line (>). The file gets written, but there is still a crash afterward.

I'd post the full stack trace, but I think this is easily reproducible? If not, I can post it.

**Comment by sichvoge** [comment]
So the example inside the repo works perfectly fine without any problems. I also have other 1.0 files that works fine. Can you share your RAML so that we can try to reproduce it.

**Comment by sichvoge** [comment]
Can you try to execute the script.js file inside the example/raml1.0 directory and let me know if that worked for you.

**Comment by beno** [comment]
I get the same results

    $ node ./examples/raml1.0/script.js 
    (node) v8::ObjectTemplate::Set() with non-primitive values is deprecated
    (node) and will stop working in the next major release.

    ==== JS stack trace =========================================

    Security context: 0xae16b9c9e59 <JS Object>#0#
    1: .node [module.js:568] [pc=0x2168e38f2984] (this=0x28658c7e6d31 <an Object with map 0x1356cf417d41>#1#,module=0x169c1eb15171 <a Module with map 0x1356cf418319>#2#,filename=0x169c1eb150f9 <String[95]: /Users/michel/Documents/Projects/RAML1.0/raml2html/node_modules/fsevents/build/Release/fse.node>)
    2: load [module.js:~449] [pc=0x2168e35533b6] (this=0x169c1eb15171 <a Module with map 0x1356cf418319>#2#,filename=0x169c1eb150f9 <String[95]: /Users/michel/Documents/Projects/RAML1.0/raml2html/node_modules/fsevents/build/Release/fse.node>)
    3: tryModuleLoad(aka tryModuleLoad) [module.js:417] [pc=0x2168e3333e5d] (this=0xae16b904189 <undefined>,module=0x169c1e
    ....

**Comment by byCedric** [comment]
I'm getting the same error with our raml 1.0 project _and_ the example files. 

Here is my stacktrace, almost identical but maybe it can help: https://gist.github.com/byCedric/c1000dbb15218f389b95a1eaa4d6c3df.

**Comment by sichvoge** [comment]
Hi guys, can you describe me step-by-step what you have done so I can try to reproduce it. With the installation I have now it works fine.

**Comment by sichvoge** [comment]
My environment is using node v5.1.0. Seems that this issue comes from the node version.

**Comment by bentsai** [comment]
I was using node v6.1.0 (also on `raml1.0` branch against v1.0 file) and experiencing the same problem. It was not limited to writing files to disk—even outputting to console resulted in this error.

I downgraded to v5.1.0, and now the command works. So, confirming that this has to do with the node version.

**Comment by sichvoge** [comment]
Urgh. Anyone knows a solution to that?

**Comment by nickburns2006** [comment]
As a note, the change to node v5.1.0 works for `raml1.0`, but doesn't for `raml1.0_new`.

Thanks for all the work, guys. Love it.

**Comment by kevinrenskers** [comment]
The raml1.0 branches are gone, and I have not seen similar problems in the develop branch. Closing this for now, let's test this again on the 4.0.0-beta2 version when that's ready.
