### ISSUE TITLE
TypeError: value.match is not a function

### ISSUE THREAD

**Issue by Prochitaem** [raml2html/raml2html#224]
Seems like parser error, but I could not find where it comes from. 
Same results with Win7 node.js 4.4.5
Ubuntu 16.04 node 4.2.6
using raml2html from raml 1.0 branch
raml files created with Atom (see attached zip).
[test.zip](https://github.com/raml2html/raml2html/files/318874/test.zip)

**Comment by sichvoge** [comment]
I get a different error, but that is (I guess) related to #219.

**Comment by sichvoge** [comment]
BTW, I had to modify your example and remove `classes` from your library path.

**Comment by Prochitaem** [comment]
@sichvoge Thanks for a try :) 
Moved classes definitions into the main file - no use.
Probably some of the devs could give me a clue, how to debug all this stuff.

**Comment by sichvoge** [comment]
I usually use node-debug / node-inspector to debug that. It basically opens a browser when you execute`node-debug script.js`

**Comment by kevinrenskers** [comment]
Closing this issue.
