### ISSUE TITLE
Parameter Function Support

### ISSUE THREAD

**Issue by mikeweadley** [raml2html/raml2html#225]
I would like to improve my API documentation by leveraging parameter functions such as !singularize, !pluralize, !uppercamelcase ... defined in the 0.8 (and 1.0) specs.  I would also like to leverage multiple functions, e.g.
```
  <<resourcePathName|!uppercamelcase>> 
  <<resourcePathName|!singularize|!uppercamelcase>>
```

With an endpoint of /locations I would like to describe retrieving Locations or adding a Location to the Locations collection.

I can currently only generate HTML descriptions when using the following alone:
```
<<resourcePathName>>
<<resourcePath>>
```

**Comment by sichvoge** [comment]
Do you have an example? Not really sure what you try to achieve.

**Comment by mikeweadley** [comment]
Sorry about that. I edited the comment to insert the examples within a code block.

**Comment by mikeweadley** [comment]
Here's an excerpt from the 0.8 spec:
```
#%RAML 0.8
title: Example API
version: v1
mediaType: application/json
schemas:
  - users: !include schemas/users.json
  - user: !include schemas/user.json
resourceTypes:
  - collection:
      get:
        responses:
          200:
            body:
              schema: <<resourcePathName>> # e.g. users
      post:
        responses:
          200:
            body:
              schema: <<resourcePathName | !singularize>>  # e.g. user
  - member:
      get:
        responses:
          200:
            body:
              schema: <<resourcePathName>> # e.g. user
```
and a link to a section of the 1.0 spec:
https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md/#resource-type-and-trait-parameters

**Comment by kevinrenskers** [comment]
I'm pretty sure all this is handled by `raml-1-parser` as used by raml2obj 4 and will be part of raml2html 4 as well.

Could you beta test raml2html 4? It only works with RAML 1.0 files though.

`npm install -g raml2html@4.0.0-beta6`
