### ISSUE TITLE
Branch 1.0 failure Template render error

### ISSUE THREAD

**Issue by jerrobertson** [raml2html/raml2html#232]
I am running on Windows 7 and have built a simple raml file that causes the rendering to fail with the following error:

```
{ [Template render error: (C:\Users\jerrobertson\AppData\Roaming\npm\node_modules\raml2html\lib\template.nunjucks)
  Template render error: (C:\Users\jerrobertson\AppData\Roaming\npm\node_modules\raml2html\lib\resource.nunjucks) [Line 206, Column 53]
  TypeError: Cannot read property 'length' of undefined] name: 'Template render error' }
```

Here is the failing RAML:
```
#%RAML 1.0
title: Test raml2html
baseUri: example.com
description: Demonstrate the error in generating html from a RAML 1.0 file
version: 0
mediaType: application/json
/foo:
  get:
    responses:
      200:
        body:
          application/json:
            description: get a foo
```

The render succeeds if the response returns a 204, so I suspect the error in rendering is connected to the body element (or one of its children).

This issue may be related to #229 but that seems to be specific to fsevents (on a Mac OS)

**Comment by jerrobertson** [comment]
Figured out that the error does not occur if I specify at least one type...

**Comment by sichvoge** [comment]
So you are saying that it does not happen when you at least say:

```yaml
application/json:
  type: object
```

???

**Comment by tr3ddy** [comment]
Reproduced this bug. I guess he means a type in the types-section like:

```YAML
types:
  foo:
```

**Comment by sichvoge** [comment]
That might be a template problem. @tr3ddy or @jerrobertson Do you guys have time to look at this?

**Comment by jerrobertson** [comment]
I'm afraid I don't at the moment, sorry. @tr3ddy is correct though in that the issue is that there must be at least one type in the types section.

**Comment by tr3ddy** [comment]
Opened PR for fixing this issue in #237

**Comment by sichvoge** [comment]
Thanks @tr3ddy! Merged it.
