### ISSUE TITLE
Chrome and Firefox getting an error loading bootstrap js

### ISSUE THREAD

**Issue by gccaldwell** [raml2html/raml2html#238]
My generated html file only displays correctly on Edge. When I try to load it in Firefox or Chrome I get an "Uncaught SyntaxError: Invalid or unexpected token" pointing at bootstrap.min.js. This breaks bootstrap, giving me a terrible display on non-edge browsers.

**Comment by sichvoge** [comment]
Is your RAML valid?

**Comment by gccaldwell** [comment]
Yes, I believe so. I wrote it in the API workbench RAML editor with no warnings or errors displayed, got no errors generating the html, and the html successfully displays no Microsoft edge.

**Comment by SnareHanger** [comment]
I see this working properly in IE 11, not Firefox or Chrome.

**Comment by gccaldwell** [comment]
That is in line with what I am seeing as well.

**Comment by sichvoge** [comment]
Maybe it's because the project used an older version of the parser. Bumped that a couple of days ago. Can you try again.

**Comment by gccaldwell** [comment]
Looks like that fixed my issue. Guess I was just on the wrong side of a patch. Thanks!

**Comment by SnareHanger** [comment]
I'm still seeing this.  Uninstalled and reinstalled via npm.  Does this only work for the 1.0 spec?

**Comment by kevinrenskers** [comment]
The included example.html shows fine in Firefox, Safari and Chrome for me, no problems at all.

**Comment by kevinrenskers** [comment]
Closed due to lack of info.
