### ISSUE TITLE
Array type not support very well

### ISSUE THREAD

**Issue by lilixiang** [raml2html/raml2html#243]
Hello, I find array the array is not suppot very well.
I define a type in a file, and include the type in the main raml file.
Then define an array type using the type above.

But it renders with its type name, not the origin type properties, neither the examples.

the Type code is

```
types:
  Bank: !include types/bank.raml
  Banks:
      type: Bank[]
      minItems: 1
      uniqueItems: true
      example: 
       -
         bankId: 1
         bankName: xx.
       -
         bankId: 2
         bankName: yy
```

use code is

```
/bank/:
    displayName: displayname
      responses:
        200:
          body:
            application/json:
               properties:
                 status:
                    type: string
                    description: status
                    example:  ok
                 content:
                    type: Banks
```

it renders as:

![image](https://cloud.githubusercontent.com/assets/3169896/17277202/a9e53032-576f-11e6-9324-1f573f360867.png)

**Comment by sichvoge** [comment]
Guess the problem here is that we might need to parse `type: Bank[]` into 

```yaml
type: array
items: Bank
```

in raml2obj. But that should really be done in the parser. I will create an issue there. Can you check if it renders the second "expand" type?

**Comment by sichvoge** [comment]
Created that enhancement request: https://github.com/raml-org/raml-js-parser-2/issues/407

**Comment by lilixiang** [comment]
@sichvoge  OK，thank.

**Comment by kevinrenskers** [comment]
@sichvoge is this already done in the RAML JS parser or does raml2obj still need to get on this?

**Comment by sichvoge** [comment]
I will need to get this into their next sprint. Good call!
