### ISSUE TITLE
raml2html 2.5.0, 3.0 and 4.0 news

### ISSUE THREAD

**Issue by kevinrenskers** [raml2html/raml2html#245]
Hey all, I have some very good news to share! The RAML Workgroup has asked me to work on raml2html over the coming weeks to finally implement that new default template that I've talked about for so long, and to assist with adding support for RAML 1.0 where necessary. 

We've already had lots of discussions here in the tickets about features we'd like to see in the new template and what direction the raml2html project should move to. I've also discussed it with the RAML Workgroup and one of the conclusions is that we would like to maintain the goal and feel of raml2html: a simple documentation generator, something that spits out a single HTML file as its output and is easy to hack on if you want to change the look of your documentation. That was the original reason why I started raml2html and it doesn't make a lot of sense to move to a React app rendering a JSON file for example. Of course the new template will look better, will be more user friendly and will support more of the RAML features - without modals ;)

In the coming days I'll focus on reviewing PR's, merging develop to master and shipping a new raml2html 2.5.0 release, so you can expect that before the end of the week! Version 3.0 will then follow in a few weeks, with a new raml2obj version to go with it.

I'd like to stress that I'm not back as the main author or owner of raml2html so please don't stop contributing to this project. Your help is still very welcome and I'll assist with reviewing PR's so they should get merged a bit faster. Hopefully we can add a lot of new stuff in the 3.0 release so bring it on :)

Updates:

### 2.5.0 will focus on merging PR's with features like securedBy scopes, improved syntax highlighting
2.5.0 was released on August 4

### 3.0.0 will focus on ES6, Node 4 and dependency updates
3.0.0-beta1 was released on August 7
3.0.0-beta2 was released on August 8
3.0.0 was released on August 10

### 4.0.0 will focus on the new template and RAML 1.0 support
4.0.0-beta1 was released on August 10

**Comment by kevinrenskers** [comment]
2.5.0 was just released. Thank you all for the many contributions!

**Comment by kevinrenskers** [comment]
I am not up to date with the work in the RAML1.0 branch at all, and trying to merge develop into it causes some conflicts. Can somebody who worked on this branch please merge develop into their branch and solve the conflicts? Thanks! /cc @sichvoge

**Comment by kevinrenskers** [comment]
Actually, I just merged the ES6 refactor, so you'll probably have more conflicts now. Not sure how many changes were made, maybe easier to redo them in a new branch off of develop? Who wants to take a look at this?

**Comment by sichvoge** [comment]
I can try that. Just need to do some comparison on what have been done already and do the same inside the new branch. Maybe we should do that on the v3 branch?

**Comment by kevinrenskers** [comment]
There is no v3 branch. I'm going to do the new template in a new branch off of develop, let's keep raml 1.0 support also in its own branch until it's ready to merge in.

**Comment by sichvoge** [comment]
@kevinrenskers it took me a while but see https://github.com/raml2html/raml2html/pull/248

**Comment by kevinrenskers** [comment]
👍

**Comment by kevinrenskers** [comment]
I've actually decided to do an in-between breaking release because the change to Node 4 should be done asap, and #234 is pretty important to solve too.

3.0.0: update code to ES6, require Node 4, updated nunjucks and nunjucks-markdown
4.0.0 will include the new template and RAML 1 support

3.0.0-beta1 was just published to NPM. It's using raml2obj 3.0.0-beta1 too. Once everything works, I'll publish both as 3.0.0.

**Comment by kevinrenskers** [comment]
4.0.0-beta1 was just released, please check #254 for news, discussion, etc.
