### ISSUE TITLE
Custom templates

### ISSUE THREAD

**Issue by hassanshaikley** [raml2html/raml2html#255]
Do you have example templates? These files are basically empty.

Or perhaps some people have already made some nice custom templates? Thanks

https://github.com/raml2html/raml2html/blob/master/examples/custom-template-test/template.nunjucks

https://github.com/raml2html/raml2html/blob/master/examples/custom-template-test/another/subtemplate.nunjucks

**Comment by kevinrenskers** [comment]
https://github.com/raml2html/raml2html/tree/master/lib
