### ISSUE TITLE
Results bigger than 65536 characters get truncated

### ISSUE THREAD

**Issue by xyleen** [raml2html/raml2html#259]
Hey,

raml2html suffers from a bug identical as this: https://github.com/stiang/recli/issues/10 - if the output is bigger than the OS's pipe buffer, the write blocks and lets the program exit before writing the rest of HTML.

I can provide a pull request tomorrow with a fix (analogous to the recli issue fix) if you want :)

**Comment by kevinrenskers** [comment]
Thanks for the report! Using https://github.com/stiang/recli/pull/11 I should be able to fix it myself. I'll get a new release out asap.

**Comment by kevinrenskers** [comment]
Is this what you had in mind? #260

**Comment by xyleen** [comment]
That's exactly the change that fixed my situation. AFAIK there can be some edge cases when the write stream emits an error, but I don't think I'd worry about that.
