### ISSUE TITLE
Parent types are used instead of children for response documentation

### ISSUE THREAD

**Issue by alexnitta** [raml2html/raml2html#266]
I'm converting a RAML 1.0 file with version 4.0.0-beta7. I noticed that any Query Parameter that lists a type that inherits from another type will display the parent type instead of the child type. This happened when running `raml2html` from the command line with the default template.

For example, the `OutputResource` type lists the properties `completed` and `counters`. `counters` uses the `resource` type, which inherits from `base`. Instead of seeing the name and description of `counters` in the HTML output, we see the name and description of `base.` Similarly, instead of seeing the name and description of `rel`, we see the name and description of `base`.

This is related to the ongoing discussion of RAML 1.0 in #254 

Source code:

**HTML output for Response tab content:**

HTTP status code 200

Body

Media type: application/json

Type: object

Properties
abort_message: required (string)
Reason why this output was aborted, if any.

aborted: required (boolean)
True when generation was aborted.

completed: required (boolean)
True when generation is complete.

base: required (object)
The base class for all Fields and Arguments. Field objects are used by Resources to define the data they return. They include a name, a type, a short description, and a long description. Of these instance variables, only name is functionally significant, as it's used as the key for the field's value in the outgoing JSON. The rest of the instance variables are used to generate documentation. Argument objects inherit from Field, in that they share the same base set of instance variables, but are used on the input side of the API, and include validation functionality. .

id: required (string)
ID for this operation.

base: required (object)
The base class for all Fields and Arguments. Field objects are used by Resources to define the data they return. They include a name, a type, a short description, and a long description. Of these instance variables, only name is functionally significant, as it's used as the key for the field's value in the outgoing JSON. The rest of the instance variables are used to generate documentation. Argument objects inherit from Field, in that they share the same base set of instance variables, but are used on the input side of the API, and include validation functionality. .

signed_download_url: required (string)
Signed, expiring link to download this output.

signed_public_access_url: required (string)
URL for public access to this report. Expires after 2 weeks.

status_url: required (string)
URL for status of this operation.

style: required (string)
Style of output.

**Type:**
```RAML
  OutputResource:
    description: An output object.
    properties:
      abort_message:
        type: string
        description: Reason why this output was aborted, if any.
      aborted:
        type: boolean
        description: True when generation was aborted.
      completed:
        type: boolean
        description: True when generation is complete.
      counters:
        type: resource
        description: Counters generated during process.
        properties:
      id:
        type: string
        description: ID for this operation.
      rel:
        type: relative_links
        description: URIs.
      signed_download_url:
        type: string
        description: Signed, expiring link to download this output.
      signed_public_access_url:
        type: string
        description: URL for public access to this report. Expires after 2 weeks.
      status_url:
        type: string
        description: URL for status of this operation.
      style:
        type: string
        description: Style of output.
```

**Endpoint:**
```RAML
/admin:
  /catalog_dump:
    post:
      description: Returns a Pipeline Output object for a given access token.
      queryParameters:
        creator:
          type: string
          required: false
          description: Payee key of an artist on the catalogs.
        secret:
          type: string
          required: false
          description: API Secret Token.
      responses:
        200:
          body:
            type: OutputResource
            description: Output status object.
```

**Comment by kevinrenskers** [comment]
Thanks for the detailed ticket, and yep it's a known issue. It actually belongs to raml2obj, where there is already a ticket for it: https://github.com/raml2html/raml2obj/issues/15. So I am closing this one.

Actually, feel free to add your example to that ticket so we have it all in one place. Thanks!

**Comment by alexnitta** [comment]
Done, thanks!
