### ISSUE TITLE
Rendering of types as URI parameters

### ISSUE THREAD

**Issue by LairdTurner** [raml2html/raml2html#271]
Hi!

If I define a type for example
types:
  objectid:
    example:
      value: 576bca8b70fddb149c4a9e92
      description: A valid MongoDB object id.

And now I want to use it as an URI Parameter, for example

/company:
       uriParameters:
      id:
        type: objectid

In the resulting html I "only" get

URI Parameters
    customerid: required (objectid)

I don't get the description text or nor the example for the object id.

**Comment by kevinrenskers** [comment]
Which version of raml2html did you use?

**Comment by LairdTurner** [comment]
Hi!

The newest beta (12).

**Comment by kevinrenskers** [comment]
Beta 13 coming up fixing this issue.

![screen shot 2016-11-02 at 14 29 33](https://cloud.githubusercontent.com/assets/229384/19930459/d32e3186-a108-11e6-9ded-e11ee2dc016e.png)
