### ISSUE TITLE
Keyword in query parameters are not assumed

### ISSUE THREAD

**Issue by LairdTurner** [raml2html/raml2html#273]
Hi!

If I want to add a query parameter to a resource the key word definition will not be adopted.

```
#%RAML 1.0
title: Test API
version: 1
protocols: [HTTPS]
baseUri: https://test
mediaType: application/json
types:
  objectid:
    description: A valid MongoDB object id.
    type: string
    example: "576bca8b70fddb149c4a9e92"
  objectid_array:
      description: A array of objectIds
      type: string[]
      examples:
        key:
          [
            "576bca8b70fddb149c4a9e92",
            "576bca8b70fddb149c4a9e93"
          ]
/test:
  get:
     description: TEST
     responses:
        200:
          body:
            application/json:
              type: objectid_array
     queryParameters:
       user: objectid

```

![02-11-_2016_16-22-57](https://cloud.githubusercontent.com/assets/11073754/19934960/bd991fba-a118-11e6-966f-335b7fc3afbf.png)

I would expect that not objectid is displayed but user.
Or I missunderstand that concept?

**Comment by LairdTurner** [comment]
Or must I deal with such documentation that way:

```
#%RAML 1.0
title: Test API
version: 1
protocols: [HTTPS]
baseUri: https://test
mediaType: application/json
types:
  user:
    type: objectid
  objectid:
    description: A valid MongoDB object id.
    type: string
    example: "576bca8b70fddb149c4a9e92"
  objectid_array:
      description: A array of objectIds
      type: string[]
      examples:
        key:
          [
            "576bca8b70fddb149c4a9e92",
            "576bca8b70fddb149c4a9e93"
          ]
/test:
  displayName: /TEST
  get:
     description: TEST
     responses:
        200:
          body:
            application/json:
              type: objectid_array
     queryParameters:
       user:
         type: user
```

**Comment by kevinrenskers** [comment]
Hi, can you test this with 4.0.0-beta17?

**Comment by LairdTurner** [comment]
Hi Kevin!

If I compile my current raml file I get an Template render error:
Here is an excerpt:

{ Template render error: (C:\Users\r.hoeger\Downloads\raml2html-develop_beta17\lib\template.nunjucks)
  Template render error: (C:\Users\r.hoeger\Downloads\raml2html-develop_beta17\lib\template.nunjucks)
  Template render error: (C:\Users\r.hoeger\Downloads\raml2html-develop_beta17\lib\resource.nunjucks)
  Template render error: (C:\Users\r.hoeger\Downloads\raml2html-develop_beta17\lib\template.nunjucks)
  Template render error: (C:\Users\r.hoeger\Downloads\raml2html-develop_beta17\lib\resource.nunjucks)
  Template render error: (C:\Users\r.hoeger\Downloads\raml2html-develop_beta17\lib\resource.nunjucks) [Line 252, Column 85]
  TypeError: Cannot read property 'indexOf' of undefined

It has worked with beta 14.


regards

       -René

**Comment by kevinrenskers** [comment]
It's been a while, raml2html 4.0.3 has been released. Can you please test it again?

**Comment by kevinrenskers** [comment]
Closing because we're not getting responses on this ticket anymore.
