### ISSUE TITLE
errors should include correct line numbers

### ISSUE THREAD

**Issue by alexch** [raml2html/raml2html#283]
Debugging syntax errors in RAML files is tough; it's even tougher when a cryptic error message has no line number or an incorrect one.

Here's some output on my project's RAML file from the current (Dec. 1) raml2html build:

```
  parserErrors: 
   [ { code: 'YAML_ERROR',
       message: 'JS-YAML: incomplete explicit mapping pair; a key node is missed at line 278, column 56',
       path: 'campconquer.raml',
       range: [Object],
       isWarning: false },
     { code: 'YAML_ERROR',
       message: 'JS-YAML: name of an alias node must contain at least one character at line 421, column 14',
       path: 'campconquer.raml',
       range: [Object],
       isWarning: false },
     { code: 'YAML_ERROR',
       message: 'JS-YAML: unidentified alias " " at line 421, column 15',
       path: 'campconquer.raml',
       range: [Object],
       isWarning: false },
     { code: 'YAML_ERROR',
       message: 'JS-YAML: can not read an implicit mapping pair; a colon is missed at line 421, column 63',
       path: 'campconquer.raml',
       range: [Object],
       isWarning: false },
     { code: 'UNKNOWN_ARRAY_COMPONENT',
       message: 'Referring to unknown type \'Ammo\' as an array component type',
       path: 'campconquer.raml',
       range: [Object],
       isWarning: false },
     { code: 'INHERITING_UNKNOWN_TYPE',
       message: 'Inheriting from unknown type',
       path: 'campconquer.raml',
       range: [Object],
       isWarning: false },
     { code: 'STATUS_MUST_BE_3NUMBER',
       message: 'Status code should be 3 digits number.',
       path: 'campconquer.raml',
       range: [Object],
       isWarning: false },
```

As you see, the first few come from JS-YAML and have line numbers (yay!) but they are off by one (boo!). In text editors, line number counting starts at 1, not at 0, so please follow this convention.

The rest come from raml2yaml itself and are context-free. How am I supposed to know which of my dozen types is inheriting from an unknown type? Trial and error I guess.

Hopefully the line number is inside that `range: [Object]` structure and can be extracted easily for useful console output.

**Comment by kevinrenskers** [comment]
These errors come "upstream" from the [raml-js-parser](https://github.com/raml-org/raml-js-parser-2), they are not generated by raml2html.

**Comment by alexch** [comment]
I'm not calling `raml-js-parser`; I'm calling `raml2html` which is supposed to work well no matter what libraries it's using. Did you report a bug to `raml-js-parser`? If so then this bug should only be closed when that bug is closed and verified to make `raml2html` work correctly.

Please reopen this bug since it is still an issue.

**Comment by kevinrenskers** [comment]
Please read https://github.com/raml2html/raml2html#before-you-report-a-bug.

**Comment by kevinrenskers** [comment]
YOU can report the bug to raml-js-parser. The url is https://github.com/raml-org/raml-js-parser-2/issues/new.

**Comment by alexch** [comment]
As far as I can tell raml-js-parser is working fine and is giving you a `range` object which you are outputting in an unhelpful way.

**Comment by kevinrenskers** [comment]
While the range formatting could be improved indeed, the rest of your ticket was about off-by-one problems and it being context-free, which simply have nothing to do with raml2html.

**Comment by kevinrenskers** [comment]
The title of your ticket is even about line numbers. Please open a new ticket about expanding the range object, but other then that this really is not raml2html's problem to solve.
