### ISSUE TITLE
dropping raml 0.8 support, instead of supporting both just made my life hell

### ISSUE THREAD

**Issue by naterkane** [raml2html/raml2html#286]
i've been having to use a private fork of raml2html (behind firewall, using nexus not npm, etc) to support generating documentation written in both raml 0.8 and raml 1.0. i was hoping that with official raml 1.0 support it would be non-breaking, but it seems that wasn't the case.

**Comment by naterkane** [comment]
sorry for the dramatic title, but i was just genuinely shocked

**Comment by kevinrenskers** [comment]
Sorry, but supporting both would've taken too much time. I doubt your life is hell because of this, but you can always contribute improvements. Thanks!
