### ISSUE TITLE
examples from `!included` file not shown when provided as `value`.

### ISSUE THREAD

**Issue by ulaBLUE** [raml2html/raml2html#288]
Hello,

I have .json example as below. It shows properly in API workbench but did not render when converting RAML to HTML. I use version 4 since  the raml is 1.0 if that helps.

Thanks in advance.

**.raml**
```
example:
     strict: false
     value : !include examples/sample1.json
```

**it is rendered as** 

![json](https://cloud.githubusercontent.com/assets/16258310/21004918/17123208-bd33-11e6-9b7d-6abf89cc8530.png)

**in API workbench** ( shows the included .json )

![image](https://cloud.githubusercontent.com/assets/16258310/21005051/9823e968-bd33-11e6-96ed-e4cf33491a6f.png)

**Comment by ulaBLUE** [comment]
@kevinrenskers  Is there a patch planned for this bug ? thanks for your time.

**Comment by kevinrenskers** [comment]
Sadly I really don't have time at the moment to work on raml2html. It would be great if you could try to fix the bug yourself and contribute a fix?

**Comment by ulaBLUE** [comment]
Ok I see. I would really like to but don't know where to start. I shall check the source codes.

**Comment by kevinrenskers** [comment]
I'll try to find some time today to at least look into it.

**Comment by kevinrenskers** [comment]
Hm in my initial test it all works just fine. Can you add a minimal RAML file to reproduce the problem?

**Comment by ulaBLUE** [comment]
Thanks Kevin. I was using 4.0.3 beta version and seems the problem is fixed with latest one. 
sorry for the trouble. I shall close this.

**Comment by kevinrenskers** [comment]
No problem.
