### ISSUE TITLE
errors should include line numbers

### ISSUE THREAD

**Issue by alexch** [raml2html/raml2html#289]
Let's try https://github.com/raml2html/raml2html/issues/283 again.

1. Debugging syntax errors in RAML files is hard
2. Line numbers are important for debugging syntax errors
3. `raml2html` should tell me the line numbers my errors happen on
4. `raml-js-parser` returns a `range` object which probably includes some line numbers but `raml2html` prints it as `range: [Object]` which is not helpful

desired behavior: raml2html prints line numbers with errors

**Comment by kevinrenskers** [comment]
Should be a lot better now by using JSON.stringify. Errors are not processed in any other way.

**Comment by alexch** [comment]
Awesome! This is exactly what I needed. Thanks.
