### ISSUE TITLE
[raml2html 4]Upgrade Raml 0.8 to Raml 1.0, using raml2html, all json schemas are missing.

### ISSUE THREAD

**Issue by lijinma** [raml2html/raml2html#290]
As the Raml 1.0 document says, the json schema is still supported.

    types:
        Person: !include person.json

But, in my output.html, the response body is blank.

And I dumped the response.body in `resource.nunjucks`, and the schema is only the name: `Person`

Could you help me?

**Comment by lijinma** [comment]
If you don't plan to support json schema in raml2html, is there a good way to convert many json shemas to raml files?

Thanks a lot.

**Comment by kevinrenskers** [comment]
At the moment we're not rendering schema's since there were too many problems with that. I am hoping that someone will contribute a good solution. I am closing your ticket though since we already have open tickets about schema rendering. 

Sorry for the inconvenience.

**Comment by lijinma** [comment]
@kevinrenskers  Dear kevinrenskers, thanks for your response, but is there any way for me to convert the json schema to a raml data type ?

Because there are many json schema to be converted.

**Comment by lijinma** [comment]
Or could you kindly give me some instructions, like using raml2obj ?

**Comment by kevinrenskers** [comment]
I honestly don't know, sorry.

**Comment by lijinma** [comment]
@kevinrenskers Thanks, i'll try.

**Comment by sichvoge** [comment]
@kevinrenskers didn't we have a solution to display either RAML data types or the pure string (JSON, XML, or what ever) in the very very first beta version on the raml1.0 branch? Could we check that and see if we can bring it back?

**Comment by lijinma** [comment]
@sichvoge It sounds good, the json schema can be displayed as raw data. If possible, I can converted the json schema to raml data type gradually, little by little.

**Comment by lijinma** [comment]
@sichvoge Many many thanks, you idea inspire me and I made it.

1. first change `schemas:` to `types:`;
2. Use the custom template, and add the following code in resource.nunjucks.

```
{% if not b.type and types[b.schema] %}
  <p><strong>Schema</strong>:</p>
  <pre><code>{{ types[b.schema].content | escape }}</code></pre>
{% endif %}
```

I am using `types` variable, and it works perfectly.
