### ISSUE TITLE
SecuritySchemes and scopes: Information incomplete in "Security" tab

### ISSUE THREAD

**Issue by Dudenessism** [raml2html/raml2html#291]
I noticed an issue when using scopes in SecuritySchemes and scopes. 
Here's an example of the results I got using SecuritySchemes without scopes.
      securedBy: [ oauth_2_0 ]
![2016_12_12_15_50_37_xci_external_client_interface_api_documentation](https://cloud.githubusercontent.com/assets/24321710/21116385/6014a15e-c083-11e6-9a7e-3da730cc7691.jpg)

Here's and example with scope:
securedBy: [ oauth_2_0: { scopes: [ OPERATOR] } ]

![2016_12_12_15_51_53_xci_external_client_interface_api_documentation](https://cloud.githubusercontent.com/assets/24321710/21116417/7e3443a6-c083-11e6-84b8-0816ead51079.jpg)

The information about the headers is missing (which I would really like to have) where the red rectangle is located.

Here is what my raml file looks like:

<pre>
#%RAML 1.0
title: XCI / External Client Interface
version: v1
baseUri: https://test.com/xci/
mediaType:  application/json
securedBy: [oauth_2_0]
securitySchemes:
  oauth_2_0: !include securitySchemes/oauth_2_0.raml
types:
  OperatorSessionToken: #jeton de l'opérateur
    type: string
  OperatorInformation:
    type: object
    properties:
      id:
        type: number
      name:
        type: string
      status:
        type: OperatorStatus
    additionalProperties: false
  OperatorStatus:
    enum: [ Active, Inactive ]
  TransactionInformation:
    type: object
    properties:
      id:
        type: number
      transaction:
        type: TransactionType
      amount:
        type: string
      timestamp:
        type: datetime
      product:
        type: Product
  TransactionType:
    enum: [ Debit, Credit ]
  Product:
    type: object
    properties:
      id:
        type: number
      name:
        type: string
      operator:
        type: string
/operators:
  /operator:
    get:
      description: Obtain operator information
      securedBy: [ oauth_2_0 ]
      headers:
        OperatorSessionToken:
          description: Operator Session Token
      responses:
        200:
          body:
            type: OperatorInformation
        500:
          body:
            type: string
/accounts:
  /account-{AccountId}:
    description: a specific account ID
    uriParameters:
      AccountId:
        type: integer
    get:
      description: Getting information on a specific account
      securedBy: [ oauth_2_0: { scopes: [ OPERATOR] } ]
      headers:
        OperatorSessionToken:
          description: Operator Session Token
      responses:
        200:
          body:
            application/json:
              type: string
        500:
          body:
            type: string
/transactions:
  /transaction-{TransactionId}:
    description: a specific transaction ID
    uriParameters:
      TransactionId:
        type: integer
    get:
      description: Getting information on a specific transaction
      securedBy: [ oauth_2_0: { scopes: [ OPERATOR] } ]
      responses:
        200:
          body:
            type: TransactionInformation
        500:
          body:
            application/json:
              type: string
</pre>

**Comment by psychoo118** [comment]
As I can see the warning box(with yellow background) looks good because 'renderSecuredBy' js function is used to render it. 

In situations when no scopes are defined a method's securedBy property will be like
``` JSON
"securedBy": [
  "oauth_1_0",
  "oauth_2_0"
]
```
It will be displayed properly nothing is wrong. But after specifying scopes for a method it will look like:
``` JSON
"securedBy": [
  "oauth_1_0",
  {
    "oauth_2_0": {
      "scopes": [ "OPERATOR" ]
  }
]
```

Both views(warning box and the tab pane) are rendered by looping through the securedBy property of a method within the template and the problem is that every value in the array are treated as strings, which is not the case when scopes are defined. I feel a little bit of inconsistency here and as I'm new here I don't know if I feel right. I can also see that it is coming from raml-js-parser-1 and raml2obj leaves it as it gets.

So maybe @kevinrenskers could help me out and we could figure out a fix for it. One solution is that we create a renderer function in JavaScript for the tab pane too(which I don't really like since it would be a little bit hacky solution, maybe good for a temporary fix). But in the long-term it should be converted into a more consistent structure to make our lives easier.

**Comment by Dudenessism** [comment]
I don't know if it's a good solution but I added a function in the index.js file that goes like this. It return the key value instead of reading the object as a string.
<pre>
  // Parse securedBy and use scopes if they are defined
      ramlObj.getSecurityScheme = function (securedBy) {
        let out = '';
        if (typeof securedBy === 'object') {
          out += Object.keys(securedBy)[0];
        } else {
          out = securedBy;
        }
        return out;
      };
</pre>

And then modified the resource.nunjucks template to include the call to this function so that it would be rendered:

                     {% set renderableSecuredBy = getSecurityScheme(securedBy) %} 
                     {% set securityScheme = securitySchemes[renderableSecuredBy] %}
                     <h1>Secured by {{ renderableSecuredBy }}</h1>



I just did it locally on my computer because I wanted to see if it made any sense. I had completely forgotten I had opened this issue. Feel free to use it if you consider it a good fix (and not just a workaround).

**Comment by psychoo118** [comment]
I think it looks quite good :)
