### ISSUE TITLE
Relative refs in included json files not resolved correctly.

### ISSUE THREAD

**Issue by jjjasper** [raml2html/raml2html#294]
When a raml file includes a json schema that is in a different directory, eg

````yaml
type: !include schemas/my-type.json
````

and my-type.json in turn refers to another file in the same directory

````json
  "$ref": "my-other-type.json"
````

generation fails because the ref in the json file is resolved relative to the raml file instead of the json file that contains it.

````json
{
  "parserErrors": [
    {
      "code": "EXAMPLE_SCHEMA_FAILURE",
      "message": "Example does not conform to schema: Content is not valid according to schema: Reference could not be resolved: /Users/jasper/temp/raml-doc-gen/my-other-type.json# /Users/jasper/temp/raml-doc-gen/my-other-type.json#",
      "path": "api.raml",
      "range": {
        "start": {
          "line": 88,
          "column": 12,
          "position": 2864
        },
        "end": {
          "line": 88,
          "column": 19,
          "position": 2871
        }
      },
      "isWarning": false
    }
  ]
}
````
(Copying all the json files next to the raml file can be used as a workaround.)

**Comment by kevinrenskers** [comment]
I'm not sure how raml2html would solve this, as the actual parsing of all this is done by the official raml-js-parser. Since I don't use JSON schema's at all myself, I am hoping someone (you?) can look into this problem and create a ticket for https://github.com/raml-org/raml-js-parser-2 is necessary.

**Comment by ulaBLUE** [comment]
Hi, similar [issue](https://github.com/mulesoft/api-workbench/issues/361) with XML schema references. I have filed issue in api-work-bench.

But as Kevin suggested, it is better to file in raml-js-parser.

**Comment by kevinrenskers** [comment]
Closing this, going to create a new umbrella-issue for all things $ref.
