### ISSUE TITLE
In example block show one object instead array

### ISSUE THREAD

**Issue by sluchznak** [raml2html/raml2html#296]
Hello.

I'm defined array of objects as response, but raml2html show example as single object
raml:
```yml
/city:
    get:
      description: list of all available items
      responses:
        200:
          body:
            application/json:
              type: City[]
      queryParameters:
        q:
          required: false
          description: Part of city name
          type: string
          example: "New-Y"
        expand:
          required: false
          description: Comma separated expandable inner types
          type: string
          example: "country"
```
![image](https://cloud.githubusercontent.com/assets/4091442/21227903/fffb5288-c305-11e6-9476-36057829a0db.png)

**Comment by kevinrenskers** [comment]
That's the example for one single City item. You should define the example on the body itself it you want to show it as an array, raml2html doesn't modify examples to make them into an array.
