### ISSUE TITLE
Types within RAML response not being expanded if set to optional

### ISSUE THREAD

**Issue by lijithv** [raml2html/raml2html#297]
Run **raml2html** against the sample file api.raml.

Look at the "amount" element in the GET response, and notice the complex object type is not being expanded (showing as "object object"). However, if the amount element is set as a required field, it works properly.

Sample generated HTML also included.

[bug.zip](https://github.com/raml2html/raml2html/files/656474/bug.zip)

**Comment by psychoo118** [comment]
I re-tested your attachment with release 4.1.0 and now everything is fine with it, so I will close this issue. Thanks for your report @lijithv!
