### ISSUE TITLE
Example's `description` and `displayName` not rendered

### ISSUE THREAD

**Issue by umax** [raml2html/raml2html#301]
In case of description or displayName is present in RAML, it is not rendered in output html.
RAML example:
```javascript
responses:
  200:
    body:
      examples:
        example1:
          displayName: "displayName for example1"
          value:
            first_name: "Max"
        example2:
          description: "description for example2"
          value:
            first_name: "Anton"
```

Result html:
![image](https://cloud.githubusercontent.com/assets/14619/21496496/06d95414-cc30-11e6-8b9c-c5f9463d3f7a.png)

**Comment by kevinrenskers** [comment]
True, the templates only render the example value itself. Please feel free to fix the issue and send a PR, thanks!

**Comment by psychoo118** [comment]
I tested your example with release 4.1.0 and it seems fixed for me so I will close this issue.
Thanks for your report @umax!

**Comment by umax** [comment]
Thanks!
