### ISSUE TITLE
Raml 1.0 Extension doesn't work

### ISSUE THREAD

**Issue by timeros07** [raml2html/raml2html#309]
When i write
```
#%RAML 1.0  Extension
extends: ../modules/common.raml
```
paths from common.raml file is not included in result html.

**Comment by kevinrenskers** [comment]
Hey @timeros07, sorry for the lack of replies. Could you please move this issue to raml2obj? Maybe even add a failing unit test via a pull request?

**Comment by timeros07** [comment]
Added:  https://github.com/raml2html/raml2obj/issues/31.

**Comment by nickburns2006** [comment]
I know that this issue is closed, but the solution is in raml-1-parser version 1.1.15, which I've submitted a PR (raml2obj#35) to update the dependency to the right version. Once that PR is merged and a new version is released, we'll need to have raml2html updated.

**Comment by kevinrenskers** [comment]
raml2html doesn't depend on a strict version of raml2obj so that won't be necessary actually.

**Comment by nickburns2006** [comment]
Sounds great. Just making sure all bases are covered.
