### ISSUE TITLE
Union Type does not render in docs

### ISSUE THREAD

**Issue by vglushonkov** [raml2html/raml2html#314]
When I set a union type:
```Property:```
```    type: PropertyType1 | PropertyType2```

Documentation just says:
`
Property: (PropertyType1 | PropertyType2)
`
With no links for both types provided.

Why not showing what is behind PropertyType1 and PropertyType2? There is no way you can get the contents of these two models from the documentation, getting the contents of them just absolutely unreachable.

**Comment by psychoo118** [comment]
As I can see raml2obj's output contains all the information required to render the super types and its' properties but the templates do not use them. In the evening I will check it and try to solve the issue.

**Comment by leflamm** [comment]
Same when using this syntax
```raml
  ArticleResponse:
    type: [ Response, Article ]
```
None of the properties of either `Response` or `Article` is rendered.

**Comment by harbesc** [comment]
Looking at @psychoo118 commit could this be fixed by merging into default-theme's as discussed here? https://github.com/raml2html/raml2html/pull/317

**Comment by ElectroLutz** [comment]
Seems to @harbesc. Could someone merge into the new branch? @kevinrenskers maybe? I'm unfortunately not much into JS development. :-/

**Comment by sichvoge** [comment]
Hi. I created a new PR on the default-theme repo to add rendering union types. https://github.com/raml2html/default-theme/pull/9.

@leflamm Can you create a new issue for multiple inheritance, please?

**Comment by leflamm** [comment]
@sichvoge done https://github.com/raml2html/raml2html/issues/361

**Comment by sichvoge** [comment]
Thanks! I'll try to find some time to see what's going on there.

**Comment by harbesc** [comment]
Thanks everyone!
