### ISSUE TITLE
object properties not rendered in body

### ISSUE THREAD

**Issue by DataGreed** [raml2html/raml2html#315]
When using example from docs:

```
#%RAML 1.0
title: Example with responses
mediaType: application/json
types:
  Invoice:
    properties:
      amount:
        type: number
        minimum: 0
      vendorName:
/invoices:
  get:
    responses:
      200:
        body:
          type: Invoice
          properties:
            id: number
```

If get just Invoice fields in output. Id field specified in properties is not rendered. The same problem goes when specifying this properties in one of resourceTypes (though it may be the same problem, dunno)

**Comment by DataGreed** [comment]
Seems like it's a problem with inheritance, because complex inheritance does not work either, e.g. another example from documentations does not show any properties at all:

```
types:
  Person:
    type: object
    properties:
      name: string
  Employee:
    type: object
    properties:
      employeeNr: integer
  Teacher:
    type: [ Person, Employee ]
```

This renderes raml2html pretty unusable right now, unfortunately :(

**Comment by kevinrenskers** [comment]
Thanks for the report! It would be a great help if you could add failing unit tests to https://github.com/raml2html/raml2obj (via a PR to the develop branch). And if you feel like it, maybe even with the fix to make the tests pass? :)

**Comment by kevinrenskers** [comment]
I am also moving this ticket by the way, since the bug has nothing to do with the rendering itself, but rather with raml2obj.

**Comment by kevinrenskers** [comment]
Could you please move this ticket over to raml2obj? Sadly I'm not actually able to move tickets (I thought GitHub added a while ago, but I must have been mistaken), so just close this one and recreate it over there. Thanks!

**Comment by DataGreed** [comment]
Sure! Moved it to https://github.com/raml2html/raml2obj/issues/27

Unfortunately I'm not good with JS, so it would be hard for me to submit any unit tests :(

**Comment by kevinrenskers** [comment]
Well, just have a look at the existing tests and see if you understand what's going on :) It's pretty easy, not a lot of knowledge needed.
