### ISSUE TITLE
raml2html not working

### ISSUE THREAD

**Issue by skvskv** [raml2html/raml2html#316]
raml2html api-v1.raml
{}

raml2html -V
4.1.0

**Comment by kevinrenskers** [comment]
Works fine with all the examples, so it must be your file. Can't really help you without seeing your raml file.

**Comment by psychoo118** [comment]
@skvskv We can only help you if you provide further details about your RAML file.

**Comment by Dudenessism** [comment]
DId you put this as the first line of your raml file?

<pre>
#%RAML 1.0
</pre>

**Comment by skvskv** [comment]
No, it's 0.8 RAML spec

The gist [comes here](https://gist.github.com/skvskv/e4c1728cf7de450a2725231b6d281f8d/306dc30e91b641934cd6e144c15a44dad3391cc9)

**Comment by kevinrenskers** [comment]
raml2html 4.x doesn't support RAML 0.8 anymore, so you'll need to update your RAML file to 1.0, or stick with raml2html 3.x.

**Comment by kevinrenskers** [comment]
Next update of raml2html will improve the error message, that `{}` was super useless of course. Sorry for that :/
