### ISSUE TITLE
Solved issues should be closed

### ISSUE THREAD

**Issue by psychoo118** [raml2html/raml2html#318]
Issues with merged fixes could be closed in order to better see what is unsolved.

**Comment by kevinrenskers** [comment]
Hey @psychoo118, I can add you as a member to the raml2html org so you can go ahead and close issues. You'll also gain push access to all 3 repo's, but it would be best to keep working via pull requests rather then directly committing to develop/master. Sounds good?

**Comment by psychoo118** [comment]
It sounds acceptable for me. 😃 Thanks for your trust! 👍

**Comment by kevinrenskers** [comment]
No man, thank *you* for your contributions! And welcome to the team :)
You'll need to have 2FA turned on to accept the invite btw.
