### ISSUE TITLE
Support for RAML 0.8 when parsing?

### ISSUE THREAD

**Issue by oshalygin** [raml2html/raml2html#320]
Getting `Error: _sourceToRamlObj: only RAML 1.0 is supported!`.  Any idea if only RAML 1.0 is supported or can I pass a different config to get RAML 0.8 to work?  I notice the CLI works but not the utility itself via `raml2html.render(ramlSpecification, defaultConfiguration)...`

**Comment by kevinrenskers** [comment]
Only RAML 1.0 is supported. Stick to raml2html 3.x for 0.8 support.
