### ISSUE TITLE
Support on Ubuntu 16.04

### ISSUE THREAD

**Issue by AidanFries** [raml2html/raml2html#321]
Hi,
I previously used raml2html on Ubuntu 12, and I recently upgraded to Ubuntu 16.04 LTS.
I have npm 3.5.2, node: v4.2.6, and I have java 1.8.0_121.

I am trying to install raml2html using the instructions on this page: https://www.npmjs.com/package/raml2html but, after the installing using npm, the command raml2html is still not recognized. Here is the console output:

```
user@COMP:~/work/$ sudo npm i -g raml2html
npm WARN deprecated node-uuid@1.4.7: use uuid module instead
npm WARN deprecated wrench@1.5.9: wrench.js is deprecated! You should check out fs-extra (https://github.com/jprichardson/node-fs-extra) for any operations you were using wrench for. Thanks for all the usage over the years.
/home/user/.npm-global/bin/raml2html -> /home/user/.npmglobal/lib/node_modules/raml2html/bin/raml2html
/home/user/.npm-global/lib
└── raml2html@4.1.1 
npm WARN optional Skipping failed optional dependency /raml2html/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.17
user@COMP:~/work/$ raml2html --version

No command 'raml2html' found, did you mean:
 Command 'caml2html' from package 'caml2html' (universe)
raml2html: command not found
```

Is there a simple explanation for this? or is there some problem on Ubuntu 16.04 ?

My overall objective is to add a step in a maven build process to generate html files from raml files (that will work on Windows and Linux). But as a first step I just want to run it manually. I am hoping that I will be able to do this using raml2html.

**Comment by kevinrenskers** [comment]
This seems like a problem with your NPM setup, but I can't test this myself as I don't have access to Ubuntu. Hopefully one of the other contributors can help.

**Comment by kevinrenskers** [comment]
Actually, I think you might be a lot better off asking this question on StackOverflow. If raml2html is not recognized by your system after installing it globally, and since raml2html has nothing to do with that install process itself, then I don't think there is a bug on our side. I'd love to help you, but I am just not able to. Many more people on StackOverflow who might!

**Comment by psychoo118** [comment]
What method did you use to install node js on Ubuntu? I have an Ubuntu 16.04 server up and running and I can look into it for you :)

**Comment by AidanFries** [comment]
Thanks for the replies.
To install node I used "sudo apt-get install nodejs".

I guess my problem might be related to the warnings that I see when I install raml2html, which are:
npm WARN optional Skipping failed optional dependency /raml2html/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.17

Or perhaps it is a sudo issue. In other words, maybe raml2html requires some other components, such as node, to not be installed as sudo?

**Comment by psychoo118** [comment]
Well it's strange, after installing node.js the same way with `apt-get` and running the commands above I get another error which is related to node since on ubuntu `node` command is `nodejs` but that's another issue since it comes from the raml2html command.

Could you send what is your output for `npm root -g`? and the value of $PATH could be helpful too. (`echo $PATH`)

**Comment by AidanFries** [comment]
Ah.... I think I might where my problem comes from. I remember when I installed node I followed a guide that suggested creating a folder called .npm-global to be used by node. Maybe this is cauing my problem. Here is the output from the commands you asked for:

user@COMP:~/work/project/module$ npm root -g
/home/user/.npm-global/lib/node_modules

user@COMP:~/work/project/module$ echo $PATH
/home/user/flyway-4.0.3:/u01/app/oracle/product/11.2.0/xe/bin:/home/user/bin:/home/user/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin

**Comment by psychoo118** [comment]
Okay, then your problem is that /home/user/.npm-global/bin/ is not in your $PATH. You can fix it by running `export $PATH:/home/user/.npm-global/bin`. As you can see during the installation npm informed you about where did it link raml2html binary in this line:
```
/home/user/.npm-global/bin/raml2html -> /home/user/.npmglobal/lib/node_modules/raml2html/bin/raml2html
```

**Comment by kevinrenskers** [comment]
Looks like `~/.npm-global/lib/node_modules` isn't in your PATH, so that's why raml2html can't be found.

**Comment by AidanFries** [comment]
That fixed my problem. Thanks a lot!
