### ISSUE TITLE
Start a way to include multiple templates/themes

### ISSUE THREAD

**Issue by kevinrenskers** [raml2html/raml2html#322]
Three different ideas that I have.

Change the `lib` folder in the raml2html repo into a `themes` folder, and move the current templates to a subfolder, so `themes/default`. And then add new subfolders for future themes. Then add a way to specify the theme name on the command line. The current `-t` parameter allows you to specify the path to a main `template.nunjucks` file, but that is mainly handy for custom themes. So we should probably add another option `-theme` to specify the name of a built-in theme. We could make the entry point for each theme `index.nunjucks`, at least that makes sense to me.

Or 

Create a brand new themes repo in the raml2html org where we add all themes as subfolders. Would make it easier to make one place for all themes with its own readme, pull requests, no need to "pollute" the main repo with theme pull requests, but most importantly: no need to publish a new version of raml2html whenever a theme is changes or added. This themes repo would be published as its own package. Either always required as a dependency of raml2html, or perhaps just as an optional extra install if you want extra themes, and keep supplying the default theme within raml2html? Not sure.

Or

Each theme will be its own repo. The officially supported ones could be hosted on the raml2html org (with the added bonus of giving push access to whoever maintains such a theme without also giving them access to other repos if that would be a concern), but also it doesn't *have* to be in our org. Anyone could make one and publish it to NPM since a theme is just a github repo with at the very least an index.nunjucks file and a package.json telling with what major version of raml2html it's compatible. All these themes could use the same keywords on NPM to make them easily discoverable and we could maintain a list somewhere perhaps, with screenshots etc.

The official theme would then also be moved into its own repo, making it easier to fork and modify. raml2html would then always depend on this default theme repo.

Another nice thing about this is that specifying which theme you want to use is pretty simple: add it to your package.json dependencies, `npm install`, and support a `-theme` parameter which takes the name of this npm package. (We'd still want to support the existing `-t` parameter to point to a local file, so we don't require anyone to create a whole module/package just for simple theme modifications).

Needless to say I think option 3 is best. We could start this process right away even though we only have the default theme. I think it would make it a lot easier to get people to contribute other themes. Unless someone thinks I'm being ridiculous, I'll get on this this weekend.

**Comment by kevinrenskers** [comment]
It might also be a cool/good idea to allow any theme to supply its own rendering logic. More specifically, what the `processRamlObj` and `postProcessHtml` functions in the default config do: setup nunjucks and markdown handling, add the `renderSecuredBy` function to the raml obj, do the actual rendering of a RAML object into a HTML file, and finally minify it. All this logic can already be overridden by the user when using raml2html as a library from your own script, but what if each theme can optionally supply their own functions in a standard way?

Then we could have themes that use completely different rendering engines, or maybe they need the RAML object to be modified just that little bit, add other functions to it, etc.

We'd still supply the default implementation within raml2html rather then the new theme repo I think, so the default theme is easier to fork and play around with, without the burden of maintain these functions with future updates. More important then that though, the current functionality of specifying a custom template that's not a full blown theme package should keep on working, so we need it in raml2html itself.

**Comment by kevinrenskers** [comment]
I'm actually very excited by all this, and again, unless there are any objections I am going to jump on this and release this as 5.0.0 betas very soon.

**Comment by nickwb** [comment]
Yes, multiple themes are definitely on my wishlist. I agree that the separate repo + npm package is an appealing combination.

Some related things on my wishlist:
* Would also be nice to support themes with multiple output files - and that probably means not dumping everything on to stdout.
* Consider how raml2html could be changed so that it more easily fit in to larger grunt/gulp/webpack build pipelines. Obviously this is already possible, but you might want to use templates which incorporate LESS/SASS etc. Maybe your API documentation is embedded in to a larger app.

**Comment by kevinrenskers** [comment]
Your first point about multiple output files.. I would think very long and hard before making that change. It's a pretty big departure and I don't really see the need?

Themes should be quite free to do whatever they want in the config object that they can supply.

5.0.0 coming up soon.

**Comment by kevinrenskers** [comment]
5.0.0 is released, together with raml2html-default-theme and raml2html-markdown-theme! 🎉
