### ISSUE TITLE
Type of array items does not render

### ISSUE THREAD

**Issue by ashlanderr** [raml2html/raml2html#323]
raml2html version: **4.1.1**
If I specify type of array like this:

```raml
/some-request:
  post:
    body:
      application/json: string[]
```

It will be rendered to `Type: array of string`
But if I do it like this:

```raml
/some-request:
  post:
    body:
      application/json:
        type: array
        items: string
```

It will be rendered to `Type: array of`

**Comment by nickwb** [comment]
Have verified this. Looks like some inconsistent parser output.

**Comment by kevinrenskers** [comment]
Can we fix it in raml2obj or does it need to be fixed in the parser?

**Comment by ashlanderr** [comment]
*First commit in wrong branch.*
I think I fix it. There was a check `Array.isArray` on property "type", but not on property "items".
