### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by drobison** [raml2html/raml2html#329]
When running from the command line, I receive this message and an empty html file: "Maximum call stack size exceeded"

**Comment by nickwb** [comment]
Hi @drobison - Please specify which version of raml2html you've encountered the issue with. Also, can you provide the troublesome raml, or a raml test case which replicates the issue. That'll allow us to look at it further.

**Comment by praveendath92** [comment]
@nickwb , We ran into the same issue today. I will just layout what triggered the issue for us.

- we defined a custom type
- used the custom type to define the type of a GET response
- added an json example for the same response 

My best guess is that it happens while matching the json example with the type info.

**Comment by praveendath92** [comment]
@nickwb , @drobison , This could be due to a cyclic dependency. I can reproduce this with the below example.

```raml
#%RAML 1.0
title: Cat service
version: v1
baseUri: https://example.com
types:
    Owner:
        type: object
        properties:
            name: string
            cats?: Cat[]
    Cat:
        type: object
        properties:
            name: string
            owner: Owner


/cat:
    get:
        responses:
            200:
                body:
                    type: Cat
                    example: |
                        {
                            "name": "fluffy",
                            "owner": {
                                "name": "minion"
                            }
                         }


```

Maybe the implementation of type checking take into the option field ```cats``` for ```Owner```

**Comment by kevinrenskers** [comment]
It's probably related to #326.

**Comment by praveendath92** [comment]
@kevinrenskers , I think fixing #326 alone wouldn't fix this. There's an infinite recursion (iteration) as long as the optional property of a field is not considered - if the developers would like to address this kind of pseudo cycles in types.

**Comment by praveendath92** [comment]
Obviously this can be workaround by the API document writers by redefining the types.

**Comment by nickwb** [comment]
Is solvable doing something like this. Not sure if this is the best method though.

```patch
diff --git a/consistency-helpers.js b/consistency-helpers.js
index 34e9d05..d94f6c0 100644
--- a/consistency-helpers.js
+++ b/consistency-helpers.js
@@ -2,8 +2,16 @@ function _isObject(obj) {
   return obj === Object(obj);
 }
 
+let isConsistent = Symbol('raml2obj:isConsistent');
+
 function makeConsistent(obj, types) {
   if (_isObject(obj)) {
+
+    if(obj[isConsistent]) {
+      return;
+    }
+    obj[isConsistent] = true;
+
     if (obj.type) {
       if (Array.isArray(obj.type)) {
         obj.type = obj.type[0];

```

**Comment by eric-jahn** [comment]
I also get this same message running within a custom script.
RangeError: Maximum call stack size exceeded
    at Object (native)
    at baseGetTag (/home/eric/workspace/ramlconv/node_modules/oas-raml-converter/node_modules/lodash/lodash.js:3078:51)
    at isFunction (/home/eric/workspace/ramlconv/node_modules/oas-raml-converter/node_modules/lodash/lodash.js:11667:17)
    at isArrayLike (/home/eric/workspace/ramlconv/node_modules/oas-raml-converter/node_modules/lodash/lodash.js:11347:58)
    at Function.includes (/home/eric/workspace/ramlconv/node_modules/oas-raml-converter/node_modules/lodash/lodash.js:9449:20)
    at Raml10ResourceConverter.mapResource (/home/eric/workspace/ramlconv/node_modules/oas-raml-converter/lib/raml10/raml10ResourceConverter.js:64:11)
    at Raml10ResourceConverter.mapResource (/home/eric/workspace/ramlconv/node_modules/oas-raml-converter/lib/raml10/raml10ResourceConverter.js:66:23)
    at Raml10ResourceConverter.mapResource (/home/eric/workspace/ramlconv/node_modules/oas-raml-converter/lib/raml10/raml10ResourceConverter.js:66:23)
    at Raml10ResourceConverter.mapResource (/home/eric/workspace/ramlconv/node_modules/oas-raml-converter/lib/raml10/raml10ResourceConverter.js:66:23)
    at Raml10ResourceConverter.mapResource (/home/eric/workspace/ramlconv/node_modules/oas-raml-converter/lib/raml10/raml10ResourceConverter.js:66:23)

**Comment by sichvoge** [comment]
It seems you are using the oas-raml-converter? Is that correct?

**Comment by eric-jahn** [comment]
Yes, to first convert .8 raml to 1.0 raml, before running raml2html.  Thank
you!

**Comment by sichvoge** [comment]
MH, could you separate the issue inside raml2html or oas-raml-converter? It seems that its the converter that is having issues, no?

Also, why not using an older version of raml2html that supports 0.8?

**Comment by eric-jahn** [comment]
I probably will use an older version.  Just reporting a bug on the latest.
How far back would I have to go, yet still have the same html look as
current?  Thanks

**Comment by eric-jahn** [comment]
by the way, I can point you to the exact raml I used, since it's open
source.

**Comment by kevinrenskers** [comment]
You'll need to use raml2html 3.x for 0.8 support.

**Comment by eric-jahn** [comment]
Thanks, will use raml2html for now.  btw, here is the the directory containing the raml 1.0 that is causing the error: https://github.com/hmis-api/2014-hmis-api/tree/master/api-markup

**Comment by sichvoge** [comment]
yes please, @eric-jahn can you share your RAML with us.

**Comment by sichvoge** [comment]
can you do me a favour and add content to the RAML 1.0 api.raml, please?

**Comment by jefflage** [comment]
I am using a v1 RAML, and I get the same failure.  I don't know what it does, but I can confirm the the patch suggested by @nickwb prevents the error.  My RAML is fairly large, but I'd be happy to provide it if anyone wants it.

**Comment by kevinrenskers** [comment]
Can someone open a pull request with the fix? Happy to merge it.

**Comment by jefflage** [comment]
since the issue is actually with raml2obj, i just forked that repo to implement the fix.  however, it doesn't see to have an issue on the master/development branch.  without the fix suggested about, raml2obj is still able to parse my raml.  however, it fails to parse through raml2html.  i'm not sure where to go next.

**Comment by jefflage** [comment]
Actually, I just realized on comparing apples to apples.  I'll keep looking.

**Comment by jefflage** [comment]
@kevinrenskers I've figured it.  The issue is with the version of `datatype-expansion` that is pulled in by `raml2obj`.  For `raml2obj`, the latest version is 5.6.0.  On that version, package.json pulls in version 0.1..15 of `datatype-expansion`.  However, the current development branch of `raml2obj` pulls in version 0.2.4.  As as soon as there is a new release of `raml2obj` that bumps the version of `datatype-expansion`, this issue will go away.

**Comment by jefflage** [comment]
@kevinrenskers Ok this will be the last time I bother you with this.  I'm fairly certain I'm right.  I can get the `raml2obj` project to fail to parse my schema by doing the following:
1. clone the repo.  work off of development branch
2. delete package-lock.json
3. modify package.json to install `datatype-expansion:0.1.15`
4. run `npm install`
5. get a node shell and try to parse my RAML.  It fails due to max recursion

So thats good.  Unfortunately, if I install `raml2html`, delete `./node_modules/datatype-expansion` and then install `datatype-expanse@0.2.4`, it doesn't fix the upstream problem, which is what I expected.

**Comment by kevinrenskers** [comment]
I’ll release the update soon! :)

**Comment by jefflage** [comment]
FWIW, I did finally confirm that I can get my RAML output has HTML if I get the correct version of `raml2obj` and by extension `datatype-expansion`.  Its much harder to trick npm then it used to be!  Thanks for bearing with me.

**Comment by kevinrenskers** [comment]
New raml2obj has been released, which uses the new datatype-expansion. Please let me know if that fixes this issue and the ticket can be closed. If not, a PR with a fix would still be welcome :)

**Comment by jefflage** [comment]
`raml2obj@5.7.0` fixes this issue for me.  As far as I'm concerned, this can be closed.
