### ISSUE TITLE
Update raml2obj dependency to 5.x

### ISSUE THREAD

**Issue by kevinrenskers** [raml2html/raml2html#330]
We'll need to fix the templates to deal with the breaking changes to securitySchemes and securedBy.

This is an important update as it fixes multiple issues, also regarding inconsistencies with array types.

**Comment by kevinrenskers** [comment]
@nickwb do you maybe have time for this one of these days? raml2obj 5.1.0 is out now, and contains even more important fixes.

**Comment by nickwb** [comment]
Hey @kevinrenskers - Sorry for the radio silence, my employer has been keeping me extremely busy. I'll see if I can find time over the next few days.

**Comment by kevinrenskers** [comment]
@nickwb yea it would be great if you could find some time for this, as you were also involved in making those breaking changes in raml2obj right?
