### ISSUE TITLE
README.md refers to raml-js-parser instead of raml2obj

### ISSUE THREAD

**Issue by freddrake** [raml2html/raml2html#336]

**Comment by kevinrenskers** [comment]
You mean the sentence "If you get parsing errors, please do not report them to raml2html: it doesn't do the actual RAML parsing. Review the error and fix your RAML file, or open a new issue at raml-js-parser."? Yeah, that's supposed to be like that. raml2obj is just a wrapper around raml-js-parser, so any parse errors will come from raml-js-parser.

**Comment by freddrake** [comment]
Sorry, I guess I was fooled by looking in node_modules (both ./node_modules and /usr/lib/node_modules) and not seeing raml-js-parser anywhere.

Very confusing, but I'm not a Node.js user, and was looking for a command-line tool.

**Comment by kevinrenskers** [comment]
It's called raml-1-parser on your filesystem (yet the github repo is called raml-js-parser-2, it's all very confusing)
