### ISSUE TITLE
OAuth 2.0 : visual scopes design mess up

### ISSUE THREAD

**Issue by jy95** [raml2html/raml2html#340]
As the title said : 

Here is the securitySchema I used : 
```
#%RAML 1.0 SecurityScheme
type: OAuth 2.0
description: A basic authentification
describedBy:
  headers:
    Authorization:
      description: Used to send a valid access token (Bearer access_token)
      pattern: ^Bearer \w+\w.+\..+$
      example: Bearer dsf.dsfdsf.dsfs
  responses:
    401:
      description: Bad or expired token.
    403:
      description: Access denied not valid privilege in ressource
settings:
  authorizationUri: https://Auth0Domain.auth0.com/authorize
  accessTokenUri: https://Auth0Domain.auth0.com/oauth/token
  authorizationGrants: authorization_code
  scopes: [all:read, all:write, admin]
```

The result of this with raml2html : 
![bug](https://cloud.githubusercontent.com/assets/9306961/24351041/a540a710-12e4-11e7-987e-76a41309d707.png)

Strange , isn't ? I expected to see only a line with all:write

Tested with raml2html 6.0 . Same with the latest version known : 6.1

Again, still no problem with api-designer:

![nobug](https://cloud.githubusercontent.com/assets/9306961/24351360/b7abe0d0-12e5-11e7-984b-e237d63d544f.png)

**Comment by sichvoge** [comment]
How did you include that into the main RAML file?

**Comment by jy95** [comment]
as a library ; just like the another issue I found : https://github.com/raml2html/raml2html/issues/339

**Comment by sichvoge** [comment]
Yep, looking at that. And without being too detailed, but it's not a library ;) You are including a fragment :)

**Comment by jy95** [comment]
Sorry, the word library is most common than fragment in my developpement ^^
