### ISSUE TITLE
custom templates remove line breaks?

### ISSUE THREAD

**Issue by whereandy** [raml2html/raml2html#342]
Hello, I noticed that line breaks appear to disappear when using a custom template. Here is my minimal template:

```
test
output

{% for resource in resources %}

{{ resource.description }}

{% endfor %}
```

and here is the output:
```
test output Auth is the top level identifier. Corp is the top level identifier. site is top level id
```

notice that the line breaks are missing. I can see in the markdown theme that there is some postprocessing to add line breaks back in -- is there a way to do this without having to use themes?

I'm using 6.1 on a Mac.

**Comment by kevinrenskers** [comment]
The default theme uses a minifier in the post processing step. And yep, when you supply a template, this default theme logic is used. 

The markdown theme doesn't add the linebreaks back in, it just doesn't minify the output :)

What's your use case? Are you trying to output markdown as well? 

The easiest solution for you would be to call raml2html as a library with your own config object. Just get the default config object and override that post processing function. Or yep, do it as a theme! Then publish it for other people to use as well :)

**Comment by whereandy** [comment]
thanks for the quick response!

Yes, I am trying to output to markdown. What I noticed is that the markdown theme does not currently have `examples` or `items` implemented yet, so basically I am just trying to write those myself. I am happy to throw it into a PR when done.

**Comment by kevinrenskers** [comment]
I'm very happy to see PR's! I can't guarantee if it'll get merged since I want to keep our markdown pretty simple, but hopefully you'll find a good balance between added info and keeping the output readable.

**Comment by kevinrenskers** [comment]
I am closing this issue for now. The easy solution is to use raml2html as a library, the nicer solution is to use themes. If many more people have the same problem then we could make the minifier configurable as a command line parameter perhaps? But for now I don't want to add that complexity to the code, considering the workarounds available and that nobody else has the same problem (yet). Hope you understand.

**Comment by kevinrenskers** [comment]
One more person with the same problem, so now it's happened twice.
https://github.com/raml2html/markdown-theme/issues/1

**Comment by kevinrenskers** [comment]
There is now a --pretty command line option to turn off minification. I still think that using raml2html as a library and supplying your own config object is the better way to go instead of always using the --pretty option on the command line every time you render documentation though :)
