### ISSUE TITLE
How to add ram2html i18n support?

### ISSUE THREAD

**Issue by netroby** [raml2html/raml2html#347]
How to add ram2html i18n support?

How to convert raml to other languages besides english?

Such as render output html into chinese language, or japanese

**Comment by sichvoge** [comment]
> How to convert raml to other languages besides English?

I think that has nothing to do with raml2html actually, but more with the RAML specification. The only thing you need to do is to define all your documentation in Chinese like 

```yaml
#%RAML 1.0
title: 你好，世界
```

I don't speak Chinese and hope that it's correct :D

> How to add ram2html i18n support?

I don't know how much text is in English actually, but you can take a look into https://github.com/raml2html/default-theme and see yourself. Maybe you can contributing to that ;)

**Comment by kevinrenskers** [comment]
Yep, like @sichvoge said it's mostly just a matter of writing the RAML file in a different language. As far as text in the template itself goes, this is not something on the to-do list but PR's are always welcome!
