### ISSUE TITLE
Top-level resource toggle buttons

### ISSUE THREAD

**Issue by gilbertg** [raml2html/raml2html#352]
Hi, the toggle buttons on the top right don't seem to work - even in your demo pages. Any plans to fix this?

~gilbert

**Comment by kevinrenskers** [comment]
I think you're talking about the index on the right? They only really work when you have lots of top level resources and room to scroll. They're not toggles, they're just links to anchors within the page, and they do work.

**Comment by gilbertg** [comment]
Ah, OK, makes sense thanks. Would be cool to have filters as well.
~Gilbert
