### ISSUE TITLE
Polymorphic types not rendered on the response tab

### ISSUE THREAD

**Issue by predrag-rakic** [raml2html/raml2html#353]
Hi all,

I noticed that if type is polymorphic:
```
types:
  TestType:
    properties:
      name: string | nil
```
it won't be rendered because `ramlObj` returned by `raml2obj` looks like this:
```
   "types": {
      "TestType": {
         "additionalProperties": true,
         "type": "union",
         "displayName": "TestType",
         "name": "TestType",
         "typePropertyKind": "TYPE_EXPRESSION",
         "anyOf": [
            {
               "additionalProperties": true,
               "type": "object",
               "displayName": "TestType",
               "name": "TestType",
               "typePropertyKind": "TYPE_EXPRESSION",
               "properties": [
                  {
                     "type": "string",
                     "required": true,
                     "key": "name"
                  }
               ]
            },
            {
               "additionalProperties": true,
               "type": "object",
               "displayName": "TestType",
               "name": "TestType",
               "typePropertyKind": "TYPE_EXPRESSION",
               "properties": [
                  {
                     "type": "nil",
                     "required": true,
                     "key": "name"
                  }
               ]
            }
         ]
      }
   }
```
This structure has `anyOf` property and lacks `properties` property expected by `raml2html-default-theme`.

I'm proposing to include additional step in `raml2obj` to unify `anyOf` property (when possible) and to add `properties` to `TestType' type, something like:
```
   "types": {
      "TestType": {
         "additionalProperties": true,
         "type": "union",
         "displayName": "TestType",
         "name": "TestType",
         "typePropertyKind": "TYPE_EXPRESSION",
         "properties": 
              {
                 "type": "string | nil",
                 "required": true,
                 "key": "name"
              }
          }
      }
```
Does that sound reasonable?

**Comment by amammes** [comment]
Hi, I see the same behavior.

#%RAML 1.0
title: broken
version: v1
baseUri: http://hostname/broken/{version}
mediaType: application/json

types:
  countryCodeEnum:
    enum:
      [
        "AF",   #Afghanistan
        "AL",   #Albania
      ]

  countryCodeSoftEnum: countryCodeEnum | string

  address_ok:
    properties:
      street: string
      country: countryCodeEnum

  address_broken:
    properties:
      street: string
      country: countryCodeSoftEnum


/ok:
  get:
    responses:
      200:
        body:
          type: address_ok

/broken:
  get:
    responses:
      200:
        body:
          type: address_broken

**Comment by sichvoge** [comment]
Hi. I don't think that solution is viable. The reason is that a processor would need to understand and parse type expressions like "string | nil" which in this case is easy, but there are much more complicated expressions. Raml2obj removes some of that complexity so any other processor can easily take the info and process it.

My suggestion would probably be to add some check for the type "union" and if thats the case start iterating through "anyOf" and rendering the appropriate content.

**Comment by kevinrenskers** [comment]
I agree with Christian, better to solve this in the templates.

**Comment by amammes** [comment]
I tested the output from my "broken.raml" example above and I got this: 

![2017-08-06_12-13-26](https://user-images.githubusercontent.com/15658871/29004617-d30fcc2e-7aa0-11e7-901e-d1cba09b9697.jpg)

If I have a type with six properties that use the pipe operator, the html would show 2^6 possible types. IMHO this should be handled at the property level and not for the whole type
