### ISSUE TITLE
Type library

### ISSUE THREAD

**Issue by arswarog** [raml2html/raml2html#359]
It is necessary to create a type library, which will allow you to partially solve the problem of union and some of the issues.

p.s. Sorry for my English

**Comment by kevinrenskers** [comment]
This should really be solved in the official RAML JS parser, but failing that, raml2obj should do the work. Contributors are extremely welcome to jump in on issues like this!

Closing this ticket though, as there are already type related issues, and "type library" by itself isn't the goal :)
