### ISSUE TITLE
No static js/css files possible in raml2html templates

### ISSUE THREAD

**Issue by fbuchinger** [raml2html/raml2html#364]
since raml2html generates a single html file as output, it is not possible to include custom js or css files. In the raml2html default templates, the required js/css files are hot-linked from cdnjs.com.

 I see two major issues with this approach:
- the  generated html file breaks when the user is offline
- it is not possible to include custom js/css files (e.g. a custom bootstrap template that cannot be hotlinked). Workarounds like hosting the custom js/css files on your own servers or "inlining" them into the html using nunjucks templates with <style> and <script> tags are not very appealing...

Therefore I suggest do add a raml2html parameter --static, that copies all "static" (i.e. non-nunjucks) files from the template path below raml2html's output.html, i.e.

```raml2html --template custom-template  --static spec.raml > spec.html```

would generate:

```
spec.html
js/
  bootstrap.js
  mycustomscript.js
css/
  bootstrap.css
  customchanges.css
img/
  mylogo.png
```
Any feedback on that?

**Comment by kevinrenskers** [comment]
This hasn't been a problem until now really, and I don't want to add the complexity of outputting multiple files to the code, and then maintain that complexity going forward.

Sorry, but a feature like this will not be added by me at least. A pull request would be welcome, but I can't guarantee that it'll be merged (depending on how much complexity it adds).

**Comment by kevinrenskers** [comment]
I also think that inlining the CSS and JS is a fine solution since the output gets minified anyway. You could of course create a build step that inlines these files into the template on demand, so you wouldn't have to maintain a template with everything included..

**Comment by wdullaer** [comment]
I am inlining custom js, css and even png images in raml2html-slate-theme.
This uses the nunjucks templating system exactly the way you describe.

I don't think this is such a bad solution.
At my previous job we used to mail each other raml2html output files with API proposals. There is real value in having just a single html as an output.

There's a bit of a cost on template development, but you pay this only once. The resulting nunjucks templates are not messier than they already are in my opinion.

**Comment by fbuchinger** [comment]
@kevinrenskers thanks for the fast reply! I acknowledge your concern regarding code complexity... will use the weekend to re-think my approach

@wdullaer which tool are you using to inline the static ressources in your theme? are you also inlining background-images referenced in your css? I can understand the simplicity of mailing a single html file, but at my current job we have to zip htmls anyway or they get eaten by the virus scanner ;-)

**Comment by wdullaer** [comment]
You can put a base64 encoded string of an image in the src attribute of an img tag.
css allows this as well, but I'm not running my css files through nunjucks right now.

The idea is that you read the file in javascript, base64 encode it, set the resulting string as a variable on the context of the nunjucks renderer and then refer to it in the template.
You can take a look at the repo to see how I've done it. The nunjucks templates are rather messy, but the javascript code should be easy enough to follow.
(javascript in this case is the code of the raml2html theme, not the client side javascript of your resulting html)

**Comment by nickwb** [comment]
One option you could investiagte: I believe it would also be simple enough to write a theme which emitted a `.tar` or `.zip` containing multiple files.

I almost took this approach for a project I worked on. However, it ended up being simpler to simply use `raml2html` as a part of a longer build process - in my example raml2html simply built a single angularjs template which was then consumed by the broader app. No doubt you could also take a similar approach with any number of different UI frameworks. That said, I do concede that this approach is not ideal for people simply which to distribute complex raml2html themes.
