### ISSUE TITLE
raml2html omits critical information about non-existent and malformed types

### ISSUE THREAD

**Issue by DataGreed** [raml2html/raml2html#365]
When rendering documentation with raml2html 4.x I've received errors when trying to render a document that references non-existent object types. In the latest (6.x) versions the document renders just fine without any warning.

It's very hard to debug the raml API definition that way as there is no way of quickly determining what may be broken in the rendered documentation. Right now I have to go through every resource and method request and response, to determine if everything renders correctly.

I understand that silent failing and replacing no-existent types output with just the type name is a design decision, but it would be great to at least have some kind of warning to know that something might be rendered in a wrong way, so I will be able to quickly find and fix it.

**Comment by kevinrenskers** [comment]
You can turn on raml validation by using the `--validate` option. It's off by default because of speed, but you can turn it on :)

**Comment by DataGreed** [comment]
@kevinrenskers thanks a lot! it hink it's worth pointing that out in readme ;)

**Comment by kevinrenskers** [comment]
`raml2html --help` ;)

**Comment by DataGreed** [comment]
@kevinrenskers by the way is it possible to still proceed with the build even if the errors were found?

**Comment by kevinrenskers** [comment]
I don't think so since its the underlaying RAML JS Parser that does all this.

**Comment by DataGreed** [comment]
Ah, okay, got it. Thanks!
