### ISSUE TITLE
Github markdown for description isn't supported

### ISSUE THREAD

**Issue by amitav13** [raml2html/raml2html#369]
The html generated doesn't seem to be respecting Github-flavored markdown for description. For example,

```raml
#%RAML 1.0
title: Broachcutter
version: 1
baseUri: https://blah.broachcutter.net
mediaType: application/json
description: |
  Exposes the SAP backend of Broachcutter to enable e-commerce functionality, except for payments.

  ###### Standard error codes
  400, 401, 403, 404, 500, 503 apply to all endpoints with their usual meanings, unless specified otherwise.
  ###### User authentication  
  User authentication will be handled by a separate service, Firebase. All requests made to this API will have a unique user ID passed in with them.
```

doesn't show the line break or the h6 tags. 

I [reported this](https://github.com/raml-org/raml-js-parser-2/issues/794) across at the parsing library and the parser seems to be reading the markdown correctly.

**Comment by kevinrenskers** [comment]
We're using https://www.npmjs.com/package/marked for the actual markdown parsing. They have an option to enable gfm, so it wouldn't be hard for us to enable it. Not sure if it would break other people's RAML files then?
