### ISSUE TITLE
Cannot use 'in' operator to search for 'types'?

### ISSUE THREAD

**Issue by ralucas** [raml2html/raml2html#370]
Getting the following error when I run raml2html from node_modules like this:  
`./node_modules/.bin/raml2html ./docs/my.raml > ./docs/index.html`  

```
node_modules/raml2obj/lib/arrays-objects.js:101
    if (key in ramlObj && ramlObj[key]) {
               ^

TypeError: Cannot use 'in' operator to search for 'types' in ./docs/my.raml
    at objectProperties.forEach (/node_modules/raml2obj/lib/arrays-objects.js:101:16)
    ...
```

But, when I run it from the global scope, i.e. 
`raml2html ./docs/my.raml > ./docs/index.html`  
it runs fine, no issues.

Both versions are 6.4.1.  Any ideas as I want to be able to run this on a build server without global dependencies?  Thanks.

Richard

**Comment by mastropinguino** [comment]
Hi,
I was into same trouble.
The problem come from raml2obj library you are using.
In my case, I uninstalled the old version and installed new one (raml2obj@5.6.0) and all things goes right.

Regards
Vincenzo
