### ISSUE TITLE
Possible types are shown multiple times

### ISSUE THREAD

**Issue by seminarian** [raml2html/raml2html#374]
Hi,

I'm using raml 1.0 and raml2html 6.4.2. I've encoutered following issue:
![screen shot 2017-12-04 at 15 57 50](https://user-images.githubusercontent.com/9881519/33559071-ea65a7da-d90b-11e7-808e-6a8188ac6424.png)

The raml is as following:

>       /style:
        description: 'Update the style of a theme. If a value has value null it falls back to the theme default.'
        get:
          description: 'Get the style for the theme of a portal. If a value has value null it falls back to the theme default.'
          responses:
             200:
               body:
                 application/json:
                   example: !include examples/themes/style/style-get.sample
                   type: portal-style-get
             404:
              body:
                application/json:
                  example: |
                    {"message": "style not found" }

portal-sytle-get type:
> type: object
properties:
  primaryColour: string | nil
  secondaryColour: string | nil
  errorTextColour: string | nil
  inverseTextColour: boolean | nil
  backgroundImage: string | nil
  logoImage: string | nil
  topBarBackgroundColour: string | nil
  topBarTextColour: string | nil
  bottomBarBackgroundColour: string | nil
  bottomBarTextColour: string | nil
  css: string | nil

This issue sometimes occurs when adding types to GET responses. Any help would be appreciated. My api.html is getting so big (due to the huge amount of redundant html being created) that the browser has trouble handling it!

**Comment by jukeblimp32** [comment]
I too have this issue and would love to have it fixed. It makes my documentation pretty much unusable.

**Comment by kevinrenskers** [comment]
Any chance one of you might be able to try to fix it? All collaboration is greatly appreciated :)

**Comment by seminarian** [comment]
Updating to version 7.0.0 fixed the issue for me! Thanks a lot!
