### ISSUE TITLE
Passing a parameter to the templates

### ISSUE THREAD

**Issue by ArtFlag** [raml2html/raml2html#377]
Hello,

I am wondering how to pass a parameter to the template from the cmd line. This would allow me to generate several outputs from the same RAML file.

For example:

`raml2htlml api.raml -o internaldocs.html -p audience='internal'`

And in the template, I could do:

```
{% if audience == 'internal' %}
   ...
{% endif %}
```

Any pointers?

Thanks!

**Comment by kevinrenskers** [comment]
All arguments are already passed into the `render` function, which passes it to the `processRamlObj` function, but the `processRamlObj` then doesn't actually accept them or give them to the template engine. This would be a rather easy fix to implement. Would you like to give it a go a send a PR?

Just make `processRamlObj` accept the options parameter and then add them to `ramlObj` under the `options` key.

**Comment by kevinrenskers** [comment]
(also, you'd have to pass your example parameter as `--audience internal`)

**Comment by ArtFlag** [comment]
Hi,

Thanks for the info, I'll give it a shot when I can. 

The issue with having the `--audience` parameter though, is that it doesn't let the user decide the tag name so that could restrict usage, in a way.

**Comment by kevinrenskers** [comment]
Hm no the parameter is "internal", see `--audience internal`. The options would get it as a key and value

```
{
  audience: "internal"
}
```

**Comment by kevinrenskers** [comment]
6.6.0 has been released
