### ISSUE TITLE
POST/PUT parameters

### ISSUE THREAD

**Issue by StyleShit** [raml2html/raml2html#386]
How do I set POST/PUT parameters?

I tries using the code from the example RAML, but it doesn't work:
```RAML
put: # HTTP method declaration
    body:
        application/x-www-form-urlencoded:
          properties:
            name:
              description: name on account
              type: string
              examples:
                example1: Naruto Uzumaki
                example2: Kevin Renskers
            gender:
              enum: ["male", "female"]
```

In addition, I tried using the example RAML as source, and I didn't see any PUT parameters, only "URI Paramaters"

https://prnt.sc/iu8wqq

**Comment by kevinrenskers** [comment]
Check out the examples: https://rawgit.com/raml2html/default-theme/master/examples/helloworld.html#helloworld__id__put or https://rawgit.com/raml2html/default-theme/master/examples/world-music-api.html. The resources with a POST endpoint definitely show the correct properties.

**Comment by StyleShit** [comment]
@kevinrenskers I'm using [slate theme](https://www.npmjs.com/package/raml2html-slate-theme) and it doesn't work for me. Any ideas why?

**Comment by kevinrenskers** [comment]
Sorry, no. Best to just ask in that repo.

**Comment by wdullaer** [comment]
I'm the author of the slate theme: there is no support for form encoded parameters in the theme right now, because I never had a need for them.
As Kevin says, its probably better to track this in the theme repo
