### ISSUE TITLE
Give access to raml-js-parser options

### ISSUE THREAD

**Issue by fantoine** [raml2html/raml2html#394]
Hi,

I recently faced a problem which could be solved by creating a custom HTTPResolver on raml-js-parser  (accessing resources behind a Basic Auth restriction).

For this case, and surely others, it could be nice to be able to give access to all raml-js-parser.
It's not a lot of work but it needs changes on raml2obj too.

**Comment by kevinrenskers** [comment]
A PR with that change would be very welcome. As this is not something that I need myself, I don't expect that this will ever be worked on, so I am closing this issue. Sorry. Like I said, please create a PR with this feature yourself and I'll have a look at it.
