### ISSUE TITLE
Traits in included files broke validation

### ISSUE THREAD

**Issue by nimblecrm** [raml2html/raml2html#398]
When I use some of my traits in any of included files, it brokes raml2html validation. I attached the minimal example that is reproducing the problem.

```$ raml2html -v -i api.raml -o api.html
Api contains errors.

INHERITING_UNKNOWN_TYPE: Inheriting from unknown type (resource.raml:5:8)
  ERROR_IN_INCLUDED_FILE: Error in the included file: Inheriting from unknown type (api.raml:16:2)
```

Commenting `is` part in `resource.raml` fixes it. Same for manual copy-pasting of `resource.raml` content. 

[str.zip](https://github.com/raml2html/raml2html/files/2379960/str.zip)

**Comment by kevinrenskers** [comment]
Please read "before you report a bug" from the readme: https://github.com/raml2html/raml2html#before-you-report-a-bug
