### ISSUE TITLE
Not Immediately Clear Whether Field is Optional

### ISSUE THREAD

**Issue by Ahimta** [raml2html/raml2html#400]
![not-immediately-clear-if-field-is-optional-or-required](https://user-images.githubusercontent.com/3470403/50624486-e3bae000-0f31-11e9-97d3-9347cb010768.png)

Would be nice, for example, if required is in red:sweat_smile:.

**Comment by freddrake** [comment]
I think it would be even better if the required/optional status were explicit either way (at least by default).

For any given API, we have to assume:

* any given reader is unfamiliar with the default, and

* the default will not be obvious, based on the mix of optional/default through the specification.

**Comment by Ahimta** [comment]
I noticed that the theme repo is more relevant and have just made a PR for both required and default: https://github.com/raml2html/default-theme/pull/30 :smiley:.
