### ISSUE TITLE
Cannot reproduce examples given

### ISSUE THREAD

**Issue by mdeselincourt** [raml2html/raml2html#403]
This project presents a relatively complex example at 

https://rawgit.com/raml2html/default-theme/master/examples/world-music-api.html

However, the source is not provided. I found a very similar project at https://github.com/raml-org/raml-examples/tree/master/others/world-music-api, however converting this project to RAML using raml2html does not fully populate the method popup windows of the example.

Since I assume this project is not responsible for raml-org, can I ask this project to please share the SOURCES for the examples, so that users can reproduce the documentation themselves and use it as a template?

**Comment by kevinrenskers** [comment]
You're looking in the wrong repo :) 
https://github.com/raml2html/default-theme/blob/master/examples/world-music-api.raml

**Comment by mdeselincourt** [comment]
Ah, it's in /default-theme/blob/, of course it is ;) 

Thank you for the fast response!

**Comment by kevinrenskers** [comment]
Well no, it's in the examples folder of `default-theme`. Blob is just a GitHub url..

**Comment by mdeselincourt** [comment]
Oh ok - I should have used the search. Thanks!
