### ISSUE TITLE
marked dependency is vulnerable to Regular Expression Denial Of Service (ReDoS)

### ISSUE THREAD

**Issue by sguillope** [raml2html/raml2html#404]
`raml2html` currently depends on `marked 0.3.12` which is affected by a Regular Expression Denial Of Service (ReDoS) vulnerability. It was fixed in `marked >= 0.4.0`.

More information about the vulnerability can be found at:
- https://www.sourceclear.com/vulnerability-database/security/regular-expression-denial-of-service-redos-/javascript/sid-6127
- https://github.com/markedjs/marked/issues/555
- https://github.com/markedjs/marked/pull/1224

**Comment by kevinrenskers** [comment]
True, but as this is a command line application that generates static html, it’s not really a problem. Sadly there are other problems with the output of newer versions of marked, but I’ll take another look.

**Comment by kevinrenskers** [comment]
I have updated all 3rd party dependencies, and it seems there were no changes to the output of raml2html. Can you (or anyone else) please test their RAML docs against the develop branch version of raml2html, so I can be sure that this is okay to release? Thanks!

**Comment by kevinrenskers** [comment]
7.3.0 was published
