### ISSUE TITLE
Validation fails without printing an error

### ISSUE THREAD

**Issue by realthargor** [raml2html/raml2html#405]
Enabling validation I get the message:
> Api contains errors.

but no other output.

adding a bit of debug output I found this, but could not figure out why the error is not logged.

> { Error: Api contains errors.
    at toError (/opt/repos/raml2html/node_modules/raml-1-parser/dist/parser/apiLoader.js:376:17)
    at /opt/repos/raml2html/node_modules/raml-1-parser/dist/parser/apiLoader.js:271:39
    at <anonymous> parserErrors: [] }

> { code: 'UNKNOWN_ARRAY_COMPONENT',
  isWarning: false,
  message: 'Referring to unknown type \'Signal\' as an array component type',
> ...

**Comment by kevinrenskers** [comment]
Strange, errors are normally definitely printed to the console. Can you post an example RAML file triggering this problem?

**Comment by realthargor** [comment]
@kevinrenskers I reduce our raml until only the error remained.
It's some how related to the include of a traits file ...
So it can be fixed three ways:
1. Remove `is: [ localized ]`
2. Replace the include `localized: !include localized.raml` with its content.
3. Replace the type `type: Signal[]` with `array`

[raml2html-405.zip](https://github.com/raml2html/raml2html/files/2955826/raml2html-405.zip)

**Comment by kevinrenskers** [comment]
Sadly it's `raml-1-parser` that is giving us an error object without any information (`parserErrors` is an empty array), so there is nothing that we can print here. I'm afraid you'll have to open an issue with them, that they pass on the errors.

**Comment by realthargor** [comment]
@kevinrenskers Could be solved with https://github.com/raml-org/raml-js-parser-2/issues/828 which is 1.1.48.
I noticed raml2html depends on raml2obj 6.1.0 which uses 1.1.47 and is also maintain by you.
Could you update the chain to use the current raml-1-parser?

**Comment by kevinrenskers** [comment]
raml2obj 6.2.0 was released with the updated version of raml-js-parser.

**Comment by realthargor** [comment]
@kevinrenskers Thanks a lot. That fixed the problem!
