### ISSUE TITLE
Security vulnerability: ReDoS in braces, a sub-dependency of nunjucks

### ISSUE THREAD

**Issue by jonaldinger** [raml2html/raml2html#407]
GitHub alerts and `yarn audit` are calling out a vulnerability with `braces`, which is a dependency of `nunjucks`. Confirmed in isolation:
```
mkdir sandbox && cd sandbox
yarn init
yarn add raml2html
yarn audit
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ low           │ Regular Expression Denial of Service                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ braces                                                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=2.3.1                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ raml2html                                                    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ raml2html > nunjucks > chokidar > anymatch > micromatch >    │
│               │ braces                                                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/786                       │
└───────────────┴──────────────────────────────────────────────────────────────┘
```

**Comment by kevinrenskers** [comment]
Thanks, but since this is a command line tool generating static content, not really a high priority issue (or really a problem at all) for this project :)

**Comment by jonaldinger** [comment]
Thanks @kevinrenskers. The issue is more that each consumer of this library will see security warnings, have to figure out for themselves whether the issue is an actual risk for them (I didn't even know what `raml2html` was when I got the GitHub alert), and then keep track of the fact that this particular security vulnerability can be ignored in their audit list. It's much more ideal to maintain a clean audit. That said, I understand that there's not a real risk here and that there are likely higher priorities.

**Comment by kevinrenskers** [comment]
Makes sense. Sadly the upgrade to the newer version of `nunjucks` is not very straightforward, but I'll see what I can do.

**Comment by jonaldinger** [comment]
Yeah I didn't have any context around upgrade complexity - darn. Really appreciate the response and feedback, Kevin.

**Comment by kevinrenskers** [comment]
I have updated all 3rd party dependencies, and it seems there were no changes to the output of raml2html. Can you (or anyone else) please test their RAML docs against the develop branch version of raml2html, so I can be sure that this is okay to release? Thanks!

**Comment by jonaldinger** [comment]
Oh wow, thanks Kevin! My specific use case isn't super involved (generating a single large page of API docs), but for my project I just confirmed that going from
```
"raml2html": "^7.2.2",
```
to
```
"raml2html": "raml2html/raml2html#develop",
```
both resolved the `braces` audit issue as well as resulted in identical generated HTML files (zero diff).

**Comment by kevinrenskers** [comment]
7.3.0 was published
