### ISSUE TITLE
Initial page load is very slow

### ISSUE THREAD

**Issue by vijijustin** [raml2html/raml2html#422]
When we use the command  raml2html xxxx.raml > index.html to create the html page , with raml2html@7.5.0 version the below script gets updated on top of the html page. 

And page is loading very slow. 

<script type="text/javascript">
  | $(document).ready(function() {
  | $('.page-header pre code, .top-resource-description pre code').each(function(i, block) {
  | hljs.highlightBlock(block);
  | });
  |  

When we remove 

$('.page-header pre code, .top-resource-description pre code').each(function(i, block) {
   hljs.highlightBlock(block);
   });

Its working fine. Now i wanna to know how to fix ? Can i use custom template to get rid of this script block?

Regards, Viji

**Comment by kevinrenskers** [comment]
Do you have a whole lot of code blocks? I've never heard complaints that this is slow.

The readme has multiple examples on how to use your own templates though, if you want to go that route 👍

**Comment by vijijustin** [comment]
Thanks a lot for your email. We are using raml2html for many years running
slowly. We were thinking it due to we have very many files and references.
Recently we moved to raml1.0 spec to get rid of slowness and found that
blocker is that 3 lines of javascript code generated on top of generated
file. As a temporary fix we forked the package default-theme and removed
those 3 lines of code and slowness issues resolved. But I really wanna know
whether you have proper fix for it. Or what's the functionality of those
removed lines in our local.

Regards Viji
Planmill

**Comment by kevinrenskers** [comment]
The functionality is simply code syntax highlighting. So if you have a LOT of code blocks, perhaps this can be slow. You could look into doing the highlighting server-side, when generating the html, upfront. A PR with such a change would be very welcome.

**Comment by vijijustin** [comment]
Thanks Kevin. I'll try to get server side fix. Actually I'm not a great
frontend developer. Still I try how to do it on server side. To inject this
script onserver side . I suppose the highlight script should be added into
HTML file itself. Right?

One more thing. We are using raml 1.0 types. But our customers needs schema
as well so we made server side script change for type conversation and
download. My manager feels we are not sure whether we are doing right thing
or not. And we would like to have it as a feature coming with raml package
itself.

Best regards,
Viji
