### ISSUE TITLE
Unable to create subheadings under the content of titles

### ISSUE THREAD

**Issue by Techrone** [raml2html/raml2html#427]
Hi I was wondering of there was if there are any support for subheadings for titles?

```raml
...
- title: Cars
   content: | 
       subtitle: Ford
...
```

**Comment by kevinrenskers** [comment]
You can use markdown in your content, so you can create headings and subheadings that way.

**Comment by Techrone** [comment]
Is there any examples that I can use or is there a documentation that explains the different ways to markdown the content?

**Comment by Techrone** [comment]
> You can use markdown in your content, so you can create headings and subheadings that way.



> You can use markdown in your content, so you can create headings and subheadings that way.

I am currently new to this and want to use this to document my API
Is there an example or a documentation that explains the way to markdown the content? Or do you have a link that can direct me there?

**Comment by kevinrenskers** [comment]
https://www.markdownguide.org/getting-started/

```
# This is a level 1 header
## This is a level 2 header
Hello there! [This is a link](https://github.com/raml2html/raml2html/issues/427). **Pretty neat!**

- bullet
- list
- here
```

etc.
