### ISSUE TITLE
RAML Validation request

### ISSUE THREAD

**Issue by dguncb** [raml2html/raml2html#435]
Is the raml validation done by the raml parser (raml js parser). I understand it is now deprecated and replaced by webapi parser.  Please let me know if this request should be under the webapi parser and another feature request made for raml2html to use web-api.

We would like to make a feature request in the validation module for it to detect when the required field has been (wrongly) added under the type definition. Currently it does not seem to detect it, but Mulesoft Anypoint Platform Designer flags it as an  error.

**Comment by kevinrenskers** [comment]
All validation and parsing is done by https://github.com/raml-org/raml-js-parser-2.

A feature request for raml2html to switch to web-api is not going to be worked on to be honest, you'd have to build this and send a pull request. I'm the only maintainer and I don't use raml2html myself anymore, so other than critical bugs, all features have to come from contributors.
