### ISSUE TITLE
Where is index.nunjucks?

### ISSUE THREAD

**Issue by marke-apexit** [raml2html/raml2html#437]
I was hoping 'index.nunjucks' as the basis of a custom template as a solution for #436.  However, although referenced in the code, I do not see index.nunjucks in this GitHub repository.

Where can I find the default index.nujucks template?

**Comment by marke-apexit** [comment]
I found the default template in the GitHub repository raml2html/default-theme.  I just wasn't expecting that since apparently the single NPM is implemented across multiple GitHub repositories?

**Comment by kevinrenskers** [comment]
Please have a look at https://github.com/raml2html/default-theme

**Comment by kevinrenskers** [comment]
No they're multiple packages across multiple repos. It's just that raml2html depends on the default theme, see https://github.com/raml2html/raml2html/blob/master/package.json.
