### ISSUE TITLE
Does not support example of 'binary/octet-stream'

### ISSUE THREAD

**Issue by cybertk** [raml2html/raml2html#55]
Like the following response example in https://github.com/mulesoft/raml-tutorial-200

```
responses:
  200:
    body:
      binary/octet-stream:
        example:
          !include heybulldog.mp3
```

**Comment by kevinrenskers** [comment]
Closing this as it's not moving forward. It'd be great to get pull requests for this, but since there doesn't seem to be any interest in actually building this feature, I am closing it for now.
