### ISSUE TITLE
RFC: new default templates

### ISSUE THREAD

**Issue by kevinrenskers** [raml2html/raml2html#89]
If you have any ideas about how the default templates should look, please add a comment to this ticket. I'm trying to come up with a list of wishes and requirements that could be given to a designer.

My wish list:

- Glance-able overview of all API endpoints and their methods
- Somehow split the top level documentation from the endpoints
- It should be easy to show/hide the individual methods
- Searchable
- Direct links to specific endpoints, methods
- Single page html output
- Hopefully not rely on bootstrap/jQuery. No external deps = no http/https problems.
- Not written in Handlebars

**Comment by ddossot** [comment]
_Copied from #97_

- **Replace pop-ups with foldable sections.**
I think it would be easier to read if the method details were in foldable sections instead of pop-ups. Consider the case when you compare two methods: you have to go back and forth between pop-ups while, if foldable sections where used, you could see both information sections on the same page.

**Comment by ttheuer** [comment]
I see that

> Direct links to specific endpoints, methods

and 

> Replace pop-ups with foldable sections

have alreade been mentioned, so all that remains is for me to +1 those.
Right now I feel that the generated documentation is not as useful as it could be. Is there any ETA for this new template?
I'd offer my help, but I'm not very good with either javascript or HTML :/

**Comment by kevinrenskers** [comment]
I can't offer an ETA, sorry. I have found a designer willing to design new templates in his free time, but it'll be a while before that's ready and then it still needs to be implemented. It's on my agenda but don't hold your breath. Sorry I can't be more specific!

**Comment by lazutkin** [comment]
> Replace pop-ups with foldable sections

:+1: 

and

:+1: foldable sections for scheme, response and request bodies

**Comment by kevinrenskers** [comment]
Good news: I've started to work on version 2 of raml2html. The first part is done: everything is based on promises and it's much more flexible for power users. For example, instead of being limited to use your own custom html templates you can now even use a completely different template engine. Speaking of which, the default templates now use Nunjucks instead of Handlebars. This got rid of all the little helper functions since Nunjucks allows for much more logic within the templates. I know that some developers are against this in principle, but we already had 6 helper functions for different kinds of conditionals... not something that I wanted to maintain in the long run.

The second part begins now: new default templates! I have a designer working a new (modal-less!) designs and I hope that it won't be *too* long before raml2html generated docs will finally have a new look and feel.

For now I am hoping to get some input on the work done so far. It would be great if you could check out the [v2 branch](https://github.com/kevinrenskers/raml2html/tree/feature/v2) and give it go. It has fairly fundamental changes (promises, Nunjucks) so it would be good to get early feedback. If you've only used the default templates via the command line then there shouldn't be any changes. I'm more interested to know how this will affect you if you've used raml2html as a library, and/or used custom templates.

**Comment by justjacksonn** [comment]
Son of a.. I am just starting to get decent with Handlebars.js too... but for another project ;). I've not heard of this nunjucks, have to check it out.

I've only been using raml2html -i file.raml -o index.html. I've not tried to do anything else with it at this time. I recall reading we could apply our on CSS to it.. but otherwise I thought the layout that is generated is it. So I am interested and possibly a good idea if you could write a bit more about this new template feature. What does it allow me to do... can I easily provide a template for how I want resources, content, and other things laid out on the page? Is there the ability to use multi-page output (like one page for each root resource endpoint)? I am thinking along the lines of the Stripes API doc... if there is a way I can combine sample code for different languages on the right side, API content/details in the middle and a left side resource links. One of our product APIs has over 500 resources though.. so I am fearful of a single html page being generated from that many endpoints.

Thank you for continued work..and I assume once 1.0 comes out you'll update this project to use 1.0 spec as well.

**Comment by kevinrenskers** [comment]
Check out http://mozilla.github.io/nunjucks/. Like I said, it's a lot easier to use simple conditionals in your templates with this, removing the need for all the small helper functions that need to be registered.

It's always been possible to use your own custom html templates, but you were stuck with Handlebars. This is now more flexible. Even though the default templates will use Nunjucks, you could continue to use Handlebars or use something completely different. If you want to use custom templates right now, just copy the defaults ones, modify them to your needs and check out the readme file for how to use your own custom templates.

Yes, if the RAML spec is finally updated then raml2html will use the new spec as well.

**Comment by kevinrenskers** [comment]
With v2 it should be easier to generate multiple html files as long as you use raml2html as a library from your own script (as opposed to using raml2html directly from the command line), using your own processRamlObj function. You'll be able to do whatever you want with the raw RAML JavaScript object. It's all up to you then though, I don't see the default templates ever being split over multiple files.

**Comment by justjacksonn** [comment]
Do you have any details/tutorials around how to use the new features?

**Comment by kevinrenskers** [comment]
Check out the source, the readme and examples/script.js.

**Comment by justjacksonn** [comment]
Alright..will do. One issue already.. maybe it's my stuff though:

expected <block end>, but found <scalar>

The offending bit of raml
get:
  headers:

stops at the line where headers: is and gives that error. The original raml2html does not have this problem. Not sure if this is a bug or not.

**Comment by justjacksonn** [comment]
expected <block end>, but found <scalar>

**Comment by justjacksonn** [comment]
Hmm.. not sure what else to do.. still seeing this with the latest. Also see this when I run npm install:

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

**Comment by kevinrenskers** [comment]
Sorry man, but I have no clue what kind of computer problems you've got going on. I'm going to remove this comments since they have nothing to do with the feedback on the new version or new designs. Feel free to make a new ticket with more info and your RAML file if your problems persist with the v2 branch.

**Comment by kevinrenskers** [comment]
I'm about to merge V2 into master this weekend. It uses the new promises-based raml2obj, uses promises internally as well. I also replaces the default Handlebars templates with Nunjucks templates. This got rid of all those annoying little helper methods, the code (and config object) got so much easier. Dealing with partials also got a lot easier, since the main template simply includes its partials.

It does not yet implement the new design, that'll come in version 3. The designs are basically finished but need to be implemented.

Anyway, version 2 is quite a big change, anyone using custom templates will either have to rewrite them to Nunjucks or use a custom processRamlObj function and keep using Handlebars - V2 will make it possible to not only use custom templates, but completely customize the render step, including using a completely different template engine. A complete example [is provided](https://github.com/kevinrenskers/raml2html/blob/develop/examples/keep-using-handlebars.js) if you want to keep using your current templates. This example also illustrates how much code I was able to get rid of with the move to Nunjucks :)

I'm quite happy with V2, I hope you guys are too. And with the new designs on the horizon, the future is nice and bright :)

**Comment by robertlevy** [comment]
this sounds great!  could we get at sneak peek at what you are thinking for the v3 template?

**Comment by kevinrenskers** [comment]
Very rough design:

![raml2html-0 3-method](https://cloud.githubusercontent.com/assets/229384/7789552/0f6f834c-0255-11e5-9909-edb689a42ffa.png)

**Comment by robertlevy** [comment]
thanks for the preview :)  love the TOC on the left and the search box (assuming that operates totally in the browser).  not a fan of having to toggle between http methods and request/response though - it's not a modal dialog but it's still modal.  
i like to see the entire api at once for 3 reasons: 
0) easier to scan over a large api set to get a high level understanding of everything it does
1) so we can print the api documentation (onto paper or to a PDF file) for archival as a project deliverable to our clients
2) to use the "find in page" feature of the browser to do a search

in our custom v1 template, we use a lot of nested collapsible panels (via bootstrap) with an "expand all" button at the top of the page so readers can choose to drill into specific things or do the "show everything" in order to search or print.

what would you think about making those toggle buttons be "multi-select" so we have the ability to see everything at once?  if not, thats cool - i think we'd update to v3 and then use this as a baseline to re-customize to fit our process a bit better

**Comment by kevinrenskers** [comment]
The toggle for request/response is probably going to go, but the toggle for the http methods is there to stay. Searching will be better with a proper search tool and for printing/pdf.. better to write a custom renderer for that, as opposed to printing the html layout? Personally I'd use [raml2md](https://github.com/kevinrenskers/raml2md) as a starting point, add what I'd want to print.

**Comment by kevinrenskers** [comment]
My biggest question is actually how to implement the new design: pre-render the entire html server-side like I do now? Or go client-side Single Page Application (SPA)?

### Pre-render (current implementation)
* Output is a single HTML file: server-side Nunjucks templates render the RAML file(s) to a single HTML file
* Easy to integrate with other systems
* Easy to hack the output
* A client-side search feature is pretty damn hard to implement
* The output is pretty big since all the modals etc are written up front, but is mostly a problem with big RAML files (also would be less of a problem when the modals are gone)

### SPA
* The idea is that raml2html basically outputs a JSON file that is then rendered client-side using a front-end framework like Angular or React (no more template rendering on the server)
* The output would thus be multiple files, unless all the JS, CSS and the RAML JSON can inlined (requiring a build step? or server-side templates that fill in the client side app like `{{RAML_JSON}}`?)
* The output would be (somewhat) smaller, especially for large RAML files
* Client side search would be pretty easy to do
* A bit harder to hack the templates,  on the other hand it's just a matter of learning Angular or React vs Nunjucks
* Probably harder to integrate into other systems

I think that the SPA approach makes more sense, especially when you consider the need for a good search feature. My big worry though is how this would still be "raml to html", it's more like "raml to json" with a SPA wrapped around that. And that SPA part never changes per different RAML doc. It's almost like the new template would be a brand new GitHub repo - simply a web app that renders a raml.json file. And then you'd have a new "raml2json" project (a tiny tiny wrapper around the existing [raml2obj](https://github.com/kevinrenskers/raml2obj)) and.. raml2html would be dead/replaced. 

Also I just made the switch from Handlebars to Nunjucks templates, not sure how everyone would like yet another big change if suddenly it would be Angular or React or something like that.

So yeah, I'm struggling with this a bit.. I keep going back and forth between the 2 options. Like, "what if we drop the search feature, and keep the Nunjucks approach?", but then I think "no that's just silly", but then I think about how huge of a change the SPA way is, etc etc :)

Input welcome!

**Comment by robertlevy** [comment]
I vote pre-render.  If looking at API docs ends up having instructions more complicated than just "hey open this file", that would probably be a upgrade blocker for us.   Our main usage of raml2html is running it from our CI scripts and then accessing the static output as an artifact.   

As for search, you could emit the json object into the body of the page and then implement the actual search functionality very similarly to how you'd do it if you had a SPA calling a nodejs service to do the work.  I'd be willing to work on a PR for this when you think the timing is right to tackle it.

**Comment by kevinrenskers** [comment]
In both cases the output would be an html file that can simply be opened. Not really a reason to vote one way or the other.

Including the JSON object into the body *and* pre-rendering the entire page will double size of the html file. In the case of the GitHub example, think 2+ MB, that's not acceptable.

**Comment by kevinrenskers** [comment]
I'd love to get input from some of the contributors, /cc @walling @dwcramer @Philzen @bitfrost @jdowggg, please see https://github.com/kevinrenskers/raml2html/issues/89#issuecomment-105079776

**Comment by justjacksonn** [comment]
I would say do it with ReactJS, go SPA and do it server side and client side, as ReactJS handles both easily.

**Comment by bitfrost** [comment]
I am biased since everything I am doing at the moment is basically React based SPA apps.  That would be the direction I would like to see things move.

**Comment by kevinrenskers** [comment]
Let's not focus on Angular vs React vs Ember, I think we should focus on pre-rendering vs SPA. I am very curious as to *why* you guys would want to go the SPA route. More specifically, how it would benefit raml2html, not just because it's what you're using in other projects ;)

What about the fact that it's yet another major change (from Handlebars to Nunjucks to SPA)? What about the difficulty of outputting a single HTML file? Because I think that is pretty important, outputting multiple files would require a lot of changes to how you use the library and command line interface. No more simple outputting to stdout for example.

What about the complexity? Outputting a simple HTML file is of course easier then using a client side framework, also for hacking it, etc. Does a client side search function weight up against all the downsides? I don't want to go SPA just because it is hip, it has to have considerable benefits. Not in the least since I'm the one stuck with building and maintaining it in the long run :)

So if you could explain your thinking instead of casting a vote, that would be very awesome, thanks!

**Comment by bitfrost** [comment]
Since it would be impossible to satisfy every UI requirement various users may have / need  I prefer the SPA approach because at it's core it starts with one big data file (JSON) that can be used to build UI as user's prefer using whatever tooling they want.  If the default template is something popular, so much the  better ... but for me the important thing is core json file / data at the base.  I think you  mention above creating a  tiny wrapper around raml2obj.

**Comment by kevinrenskers** [comment]
What you want is already possible, just write a Node script that uses raml2obj as a library, write the resulting object to disk, done. No need to use raml2html at all. All this project really is about is that default template. If you cast aside that template and only care about the core json file, no need to even use raml2html :)

So all I am thinking about at the moment is that default template, if that makes more sense as a pre-render or a SPA. The fact that the SPA approach gives you raw JSON shouldn't really be part of the decision since that's not the use case of raml2html (use raml2obj for that). Hope that makes sense?

**Comment by bitfrost** [comment]
Yep, makes sense.  You said something similar earlier in the thread:
 "And that SPA part never changes per different RAML doc. It's almost like the new template would be a brand new GitHub repo - simply a web app that renders a raml.json file. And then you'd have a new "raml2json" project (a tiny tiny wrapper around the existing raml2obj) and.. raml2html would be dead/replaced."   
As a current user of a custom template, I suspect in my next iteration I will just take this approach.  As for the SPA versus Pre-rendered.  I think if you have an output option to  inline everything in the SPA output   the approaches are not that different.

**Comment by kevinrenskers** [comment]
Yep very true.

**Comment by justjacksonn** [comment]
Is there an option to use different output generators for different formats? I could see there being several options made available rather than just one specific output style. Allowing for "plugins" so to speak would allow the community to perhaps build a SPA, multiple-page, etc.

**Comment by kevinrenskers** [comment]
The option is always to simply use raml2obj and write your own templates on top of that.

**Comment by owianbarnett** [comment]
The premise of raml2html as laid down in the opening line of the readme says "A simple RAML to HTML documentation generator" (with a similar line for raml2md).

There also is an implication that the intent is to provide a starting point to html document generation that can be customised through template customisation or rendering engine customisation. This is reinforced when you refer queries to raml2obj for a full customisable object-based starting point.

The pre-rendered approach would seem to fulfil the criteria of generating html and being simple.
In contrast the the description of the SPA proposal intimates generation of non-html (json at least as an intermediary) and a non-trivial SPA rendering client (i.e. not simple).

Based on this I would be keen to see raml2html continue to generate pre-rendered html.

For SPA cases, I can imagine and see from the preference comments in this thread that the actual choice of SPA implementation will be very much a user choice. Perhaps then there needs to be a new exemplar project for SPA cases, a raml2json + SPA client sample(s).

**Comment by kevinrenskers** [comment]
Thank you for that comment, makes a lot of sense to me.

**Comment by justjacksonn** [comment]
That's a good point @owianbarnett. Perhaps Kevin you can do the pre-rendered version as you see it shaping in to, and we can provide some feedback once you have something working.

**Comment by justjacksonn** [comment]
Ok.. this may make you cringe..but why not have both options? If I understand correctly, you currently already render (and/or are working on the v2 render) server side now. But the SPA approach is just a hosted nanjuck template that applies the raml2json output (if we went SPA approach) to build the HTML. Couldn't you add an option to do either to the raml2html CLI? If I want json, I specify --output json. If I want html, I specify --output html. I could then choose which output I want, or perhaps even both.

I think more so this opens up the doors for new templates that can transform the json output to other ways of displaying the raml help docs. Thus, you start a new project, something like raml2html-templates, where others can submit pull requests to apply new templates perhaps, and at runtime we could perhaps provide the name of the template we want to apply to the raml to json output.

You would then define the raml doc data to json format, and template writers including yourself would adhere to that format to display the docs.

Too crazy?

**Comment by justjacksonn** [comment]
Incidentally..the image "preview" you show above.. how did you generate that? I am using the 2.0.1 "develop" branch and the output is still the same. I'd love to at least try to generate that new look you have.. or did you mock that up in html and it's not ready for use by the server-side render at this time?

**Comment by kevinrenskers** [comment]
raml2html is all about that template, adding a `--output json` option doesn't make sense to me. A new raml2json project would then make more sense, that people can combine with their own templates. But like I said before, you can very easily output JSON yourself, just don't use raml2html, stick to raml2obj, write a node script that saves that output to disk, done.

That image preview in this thread is just a design mockup, no working html yet.

**Comment by justjacksonn** [comment]
Yah.. I understand. How about a new project, raml2doc, and then you specify json, html, pdf, etc. :D

**Comment by kevinrenskers** [comment]
I don't see the point so it's not something I'm going to do. I think separate projects make a lot more sense. 

Feel free to create such a project yourself though :)

**Comment by justjacksonn** [comment]
That is probably what we'll need to do. I do like the layout of the mock up though. Sort of like Stripe/Slate but without the right hand snippet of code, which I am not a fan of since it leaves so much out of how to actually use the code in an example. I also would like the option of request/response being in one page rather than tabs, but I suspect that, along with the ability to embed the resulting html into an element on an existing page could all be done with manipulating the default template for our own custom template. Can't wait for you to have this working! Few weeks or so right?

**Comment by kevinrenskers** [comment]
I hope so, not making any promises though. The Witcher 3 is kinda awesome.. ;)

**Comment by justjacksonn** [comment]
Kevin.. any update to this new layout? Is there any time frame when the new layout will be part of the raml2html build process? I'd like to use it now if possible, even if it's not completely baked yet.

**Comment by kevinrenskers** [comment]
Sorry, no news. At the moment raml2html is a bit low on my priority list, after all it does work and the new layout is "just" a nice to have. I'm planning a move to another country among other things so this just has to wait a bit. Sorry!

**Comment by MartinDesigner** [comment]
![imghome](https://cloud.githubusercontent.com/assets/13809960/9289329/0bef602c-436c-11e5-80fc-3ec07f82dd8d.jpg)
So, as a supplement, however as a main point try this amazing free app. Createer.com is an online software for easily designing online ads, responsive landing pages and print materials such as flyers, posters, covers, invitations and more. Createer lets you easily share your designs on social media, send them via email, download as HTML, image or PDF. You can even design UI mockups for mobile as for standard display (html, js, css always generating without any coding required from you). Createer also includes 3,000 predesigned templates (browse here: https://beta2.createer.com/Templates?ghi) and over 250,000 images (illustrations, photos and icons) to work with in its user-friendly drag’n’drop enviroment. And finally this amazing stuff is here: https://beta2.createer.com/?ghi

**Comment by nmors** [comment]
A dark themed option in the new template would be awesome!  

 :black_medium_square: :+1:

**Comment by jarl-dk** [comment]
I would love it to be printable, see also https://github.com/raml2html/raml2html/issues/166

**Comment by yamsellem** [comment]
@dwcrame have you cleanup your theme, so it can be used by others?

Is there another good looking theme around there?
A year seems to have passed without bringing much.

Thanks.

**Comment by sichvoge** [comment]
@kevinrenskers I'd like to take a fresh start on that with a new issue maybe consolidating / summarizing what has been discussed so far. I like the mockup that you had put in here and you also linked a branch that is not there anymore. Wonder if you still have the template for it?

**Comment by kevinrenskers** [comment]
That branch was merged a long time ago, it was for version 2.0 of raml2html, and we're at 2.4.0 now. It brought Nunjucks and Promises. 

The design mockup was never implemented as a html prototype.

**Comment by sichvoge** [comment]
@kevinrenskers do you still have the mockup? good starting point in my opinion.

**Comment by kevinrenskers** [comment]
This is the last I have:

![raml2html-changed](https://cloud.githubusercontent.com/assets/229384/16266201/e2bb7570-3883-11e6-8634-60d872aacbb1.jpg)

**Comment by kevinrenskers** [comment]
And a 2 column version which I didn't feel would work because of url lengths etc.

![raml2html-0 3-method](https://cloud.githubusercontent.com/assets/229384/16266228/06c34358-3884-11e6-81d3-c55ae862e8d9.png)

That previous one with 3 columns is what I settled on to implement before I gave away raml2html, basically :)

**Comment by sichvoge** [comment]
I would have a couple of question around the three column design. Any more direct channel that we can use, maybe where @mikestowe can listen as well?

**Comment by kevinrenskers** [comment]
I'm no longer involved with raml2html. These designs are basically all I have, do with it what you guys want :)

**Comment by sichvoge** [comment]
That's fine! @mikestowe and I, and hopefully who ever volunteers to help us, will take it from here ;)

**Comment by robertlevy** [comment]
@sichvoge - when you guys take this on, it would be great if the result was something shared with the https://github.com/mulesoft/api-designer so that these two ways of rendering RAML as HTML can evolve together

**Comment by sichvoge** [comment]
@robertlevy Mike and I will support this project independently from Mulesoft and we want to keep it that way. We put our own private time into it since we think that it is a great project and very useful for so many different use cases. I like the approach using templates to give the users more flexibility which is currently different from the direction the console is going.

Also, anyone who read that; if you are interested to help us moving that project to the next stage please let us know.
